### ISSUE TITLE
Allow nation upkeep to be per block

### ISSUE THREAD

**Issue by turtledude01** [Arckenver/Nations#100]
Title says it all, allow nation upkeep to be either per player or per block.  This would definitely be best left up to the server owner through config options.

**Comment by TheoKah** [comment]
Will add this possibility

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
