### ISSUE TITLE
[Suggestion] Zones in Admin Nations

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#102]
Allow Zones to be created in Admin Nations, this would be used for selling Shop Plots, Housing etc.

**Comment by turtledude01** [comment]
They are currently sellable, only downside is normal players can't sell zones they own in admin nations.

**Comment by yepidoodles** [comment]
Was that added after the updates? Because I tried it with v2.2 and I couldn't make zones in an Admin Nation.

**Comment by turtledude01** [comment]
Ive been using it since 2.2... you make the zones the same way you would in a player owned nation, select the corners and /z create (name)

**Comment by yepidoodles** [comment]
Hm, maybe I derped out
