### ISSUE TITLE
Configurable nation groups

### ISSUE THREAD

**Issue by turtledude01** [Arckenver/Nations#103]
The idea behind this is how Towny has/had groups within nations, where those groups could be given certain permissions and whatnot.  As an alternative to this I believe having the ability to add groups, and within those groups set if they get charged taxes, and other options like that.  Maybe even allow a nation owner to create and specify the groups permissions.

**Comment by turtledude01** [comment]
At a bare minimum, add a VIP group, which just gets exempt from taxes.

**Comment by TheoKah** [comment]
I can think of 2 groups:
- 1 exempt from taxes
- 1 exempt from taxes + have build/interaction access in all nation, but cannot set taxes or claim land

Do you have any more ideas?

For the names, We need something along the idea we had with "president", "minister" and "citizen"...
I like "officer" for the 2nd one but I have no idea for the 1st one... Unless you have a better idea, I'll probably end up with "vip"

Also I'll change the [set|del]minister command to:
- `/n rank <player>`: show a citizen rank
- `/n rank <player> <minister|officer|vip|clear>`: to set a rank

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
