### ISSUE TITLE
/n show

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#105]
No one but those with decent PC's can use /n show due to the amount of particles it creates, they fill every block instead of just the border, and the only way to disable it (That I know of) is to relog.

It also stops you from interacting with anything.

**Comment by TheoKah** [comment]
This feature is still in beta. I need to optimise it a bit more.
You can turn it off by typing the command again (just need to wait for the client to finish displaying the particules)

I'll check this interaction thing but should not be the case

**Comment by TheoKah** [comment]
Can you try with this one?

I reduced the area to mark around the player

[Nations-2.4.jar.zip](https://github.com/Arckenver/Nations/files/796305/Nations-2.4.jar.zip)

**Comment by yepidoodles** [comment]
It's still too intensive, I personally think borders like Grief Prevention's, using blocks would be much better. Shouldn't affect performance at all.

The particles are just too much.

**Comment by TheoKah** [comment]
Hmm... Ok.
I'll compile a new version that will only put particles on the ground and you tell me if it is better.

If this is still causing lag, I'll consider the GP's way of doing thing.
The reason I did not do it in the first place is because the nations are not square and can have very weird shapes.

**Comment by TheoKah** [comment]
Here.

[Nations-2.4.zip](https://github.com/Arckenver/Nations/files/801129/Nations-2.4.zip)

If this is still causing lag, I'll work on something similar to GC with "angle blocks"

**Comment by yepidoodles** [comment]
As far as I can tell this is much better, but perhaps add a delay between the particles? So they don't overlap.

**Comment by DustyMittens** [comment]
Just a random suggestion the particles are nice for a vanilla server, and players that use particles. A simple addition could be /n map and use something similar to the ASCII system based off the old factions plugin map. It will just use a few lines in the chat window and show colored "/,%, $, +, etc" of your claimed chunks/blocks whichever setup is used.

**Comment by TheoKah** [comment]
I already cleaned up a bit the particle thing on my local branch, and I plan on adding config node to choose the range of the particles.

I'll add the /n map thing like towny does in chat with # being the whole chunk claimed and * some blocks in the chunk. Should also be able to add info when mouseover.
