### ISSUE TITLE
[Suggestion] New Config Option

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#106]
So I noticed that when you make zones in nations, it takes the amount of blocks the zone used from the nation's size, allowing you to expand your nation infinitely without spending any cash. 

I personally think that zones should not affect the size of the nation at all, but this seems like it was added on purpose, so a config to turn it off would be nice

Either that or add costs to creating Zones.

- Alice

**Comment by TheoKah** [comment]
Honestly, I'm not sure if was added on purpose.

I'll check @Arckenver's code to be sure and fix this accordingly.

**Comment by TheoKah** [comment]
I was not able to reproduce this. When I claim a zone, the block count is still the same :/

**Comment by yepidoodles** [comment]
It's once you claim more land for your nation (after making zones) that it drops.
