### ISSUE TITLE
Release please, so many good things added since November :)

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#111]

**Comment by TheoKah** [comment]
I made a pre-release a few weeks ago: https://github.com/Arckenver/Nations/releases

I'm leaving @Arckenver making the releases as I don't have perms on the spongepowered page of the plugin

**Comment by Arckenver** [comment]
Hi guys,

Sure, I'll make a new official release asap. Can you provide me a changelog so I can put it along side the release ?

**Comment by TheoKah** [comment]
@Arckenver everything is here: https://github.com/Arckenver/Nations/releases (mostly under the 2.3 release)

The only commit I made after pre-releasing 2.4 is an optimisation of `/n show`

**Comment by Arckenver** [comment]
Thank you very much @TheoKah ! I've now finally [released it](https://forums.spongepowered.org/t/earth-africa-nations-v2-2-towny-like-protection-plugin/12127/185?u=arckenver), sorry for the delay.

Don't hesitate to send me an email whenever you need me to post a new release on the sponge forums !

**Comment by ProsperCraft** [comment]
Cool, but the download link on the forum post still goes to the November version.

**Comment by Arckenver** [comment]
Fixed. Thanks for reporting !
