### ISSUE TITLE
[Feature Request] White-list specified blocks to be breakable everywhere....

### ISSUE THREAD

**Issue by GazbonicAcid** [Arckenver/Nations#112]
I would like to request the ability for server admins to whitelist certain blocks to be breakable by everyone everywhere,
regardless of whatever nation(s) owns the land vs what nation a player is in.
I need this feature so that my players will be able to break their grave in protected areas (ie. the Spawn admin nation).
https://minecraft.curseforge.com/projects/gravestone-mod/

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
