### ISSUE TITLE
Chat suffix/prefix

### ISSUE THREAD

**Issue by sabbo2001** [Arckenver/Nations#113]
Hello, I'm using Nucleus, PEX and Nations. People who are in nations get their displayname suffixed by another instance of their name. Only those in nations have this issue. 

http://prntscr.com/el7120 for an example

Any ideas?

**Comment by TheoKah** [comment]
Looks like you are using another plugin that messes with chat.
If you cannot find it or are not using any, send your plugin list or a "/sponge timings report"

I'm using Nucleus, Nations and PermissionsEx myself on 5 servers with no problem

**Comment by sabbo2001** [comment]
http://prntscr.com/el74j6 these are the plugins I'm running. Do you want my PEX permission file and Nucleus configuration?

**Comment by sabbo2001** [comment]
Ok something is prefixing the chat message itself with the name (if I set chatcolour option in pex, it also changes the message's displayname)

http://prntscr.com/el75xc

**Comment by sabbo2001** [comment]
Is nations prefixing the chat message with the displayname? I note

				Text msg = Text.of(TextColors.WHITE, " {", TextColors.YELLOW, nation.getName(), TextColors.WHITE,  "} ", player.getName(), ": ", TextColors.YELLOW, ctx.<String>getOne("msg").get());

seems to re-add the player name to the main message body?

**Comment by sabbo2001** [comment]
It's only happening to people in nations, this is odd.

**Comment by TheoKah** [comment]
Where is that code from oO?

Nation doesn't re-add the player name:
https://github.com/Arckenver/Nations/blob/master/src/main/java/com/arckenver/nations/listener/ChatListener.java

I think this *might* be nucleus, can you drop your config file?

**Comment by sabbo2001** [comment]
That code is in Nations-2.4\src\main\java\com\arckenver\nations\cmdexecutor\nation\NationChatExecutor.java

**Comment by TheoKah** [comment]
Ok, this is only called when a player uses /nc message

**Comment by sabbo2001** [comment]
http://pastebin.com/URRdiXSJ config for nucleus. Again, only happening to people in nations.

**Comment by TheoKah** [comment]
put `overwrite-early-prefixes` and `overwrite-early-suffixes` to false in nucleus config, then a /nucleus reload should be enough (if not, you might have to restart)

**Comment by sabbo2001** [comment]
Pushing a restart after changing those values. Will keep you updated.

    check-body-for-minecraft-prefix=true 
is that correct?

**Comment by TheoKah** [comment]
if this is not enough, try to play with the template settings in the same section

**Comment by sabbo2001** [comment]
It's odd, sometimes it works, sometimes it doesn't. It usually stops working after a restart.

**Comment by sabbo2001** [comment]
Ok I took out jobslite and voxelsniper and it no longer seems to be doing it. If something happens I'll yell.

**Comment by sabbo2001** [comment]
Ok this is odd, if I do a /nucleus reload after restarting the server it seems to work, but only if I do that.

**Comment by sabbo2001** [comment]
It's working at the moment. I will keep you updated.

**Comment by sabbo2001** [comment]
Ok it breaks after a restart every time.

**Comment by sabbo2001** [comment]
k just removed some plugins let's see if this works 

http://prntscr.com/el81og

Not sure if it's helpful, but I'm using FTB beyond 1.2.1

**Comment by TheoKah** [comment]
I have it on beyond too with no problem... This it probably a matter of config. Also I'm not using jobs

**Comment by sabbo2001** [comment]
I dropped jobs
