### ISSUE TITLE
How do you get rid of the space before the nation tag?

### ISSUE THREAD

**Issue by Xenoyia** [Arckenver/Nations#114]
![dbfb7f860f0bbc387fa547d779da7492](https://cloud.githubusercontent.com/assets/4874985/24081920/d28b5f8e-0cb4-11e7-8b2e-d7da7d4df8c7.png)

This is _very_ ugly, I'm assuming there's a way to change it but I can't find out how.

Nucleus is formatting our chat at the moment.

**Comment by TheoKah** [comment]
What I did on my server is adding a space on nucleus' side.

I'll see if I can add a template in the config in the next version

**Comment by kristi71111** [comment]
#116 I believe that this would fix it. Already tested once and it works fine.

**Comment by TheoKah** [comment]
You can now change this in the config and remove the space
