### ISSUE TITLE
Claim/Unclaim Territory?

### ISSUE THREAD

**Issue by DustyMittens** [Arckenver/Nations#115]
I was using a test nation to see how this plugin worked, and came across something odd. Maybe intended, I don't really know? If you create a nation, and delete the single block that is your territory using /n delspawn home, use your golden axe to make a 1x1, and then type /n unclaim. You now own 0/XXXX size of blocks, but now no new territory or regions can be claimed.

Dun Dun Dun.

It might just be me, but I do like to create a town/nation, unclaim the random space it picked, and continue on my way until I find somewhere meaningful to live.

**Comment by TheoKah** [comment]
One should not be able to unclaim a block with a spawnpoint in it.
Thank you for pointing that out.

I'll also make sure a nation size cannot drop below 1

**Comment by DustyMittens** [comment]
Well the spawn point was removed, before I unclaimed the block. Should be allowed, with addition to reclaiming a new territory chunk.

Nation size shouldn't be based on blocks. (See [suggestion](https://github.com/Arckenver/Nations/issues/117))

Nation should be able to have nothing claimed until you're ready.

**Comment by TheoKah** [comment]
This should no longer be a problem with v2.5 as no block will be auto-claimed when creating a nation.
Claiming with a nation of size 0 will therefore be expected.
