### ISSUE TITLE
[Suggestion] Chunk claiming over block claiming & No Economy Option

### ISSUE THREAD

**Issue by DustyMittens** [Arckenver/Nations#117]
Like the title states. I believe the idea of block claiming is a little over complicated. I've read through random issue of block count claiming dipping into negatives, and into [infinite.](https://github.com/Arckenver/Nations/issues/95) if you wanna read it as well. 

I personally am using Nations on a FTB Beyond Sponge Test Server(Used Towny on FTB Infinity Thermos Server). 

So if you claim one chunk(**F9 if you're using any current FTB packs that outlines an entire chunk with a green box and red corners for ease of figuring out where a chunk begins and end**s) from corner to corner its 256 blocks(16x16=1 Chunk) which includes everything up, and down.

Now you're sitting at 256/1024 blocks (based on what you put per your config file) that is only 4 chunks. Over complicated for the simple player that just wants to claim his area, and start building. The need to find a corner of a chunk and go across to another corner to maximize claiming is kinda pointless. 

Just a straight claim using the axe (or /n claim with no axe needed) inside of a chunk should be sufficient enough to make it yours, have your border established, and pay your taxes/upkeep based on the number of chunks claimed, not per block(0.3 is default I believe).

 If you make that block number a non-decimal you make things more expensive based on block count rather than chunk count. Considering most servers that do use economy do not give you more than a couple hundred for joining, voting daily for a week to even start a nation, and keep it alive. 

These are just suggestions, and opinions based on using plugins (factions, towny, towny adv, etc) in a feed the beast environment instead of mods (Sponge & Nations). Hopefully Nations can become one of the best plugins for Vanilla MC & one that can support FTB protection as well in the future.

**Comment by TheoKah** [comment]
I plan to add an option for the admins to switch between fixed, per player and per block upkeep.

This being said, the claiming system were based on world edit and I admit this can cause problems for new players.

I'll see what I can do about this, but I like the idea of giving the admins the choice between the axe and the chunks. I'll see what I can do.

I should be able to work on nation later this week or maybe next week.

About the economy, this is a matter or balance I guess

**Comment by DustyMittens** [comment]
Having the choice is definitely a step in a good direction. ;D
 
The Economy thing personally I don't use it if the server doesn't have some type of player run shops or something along those lines.

Aside from that the economy portion works well from what I have tested. I'll try pushing the limits, and see if I find any other little bugs/issues.
