### ISSUE TITLE
The suggestion about police officer

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#12]
I suggest to give president a permission that endow certain player to kill and put the player into nation's jail. I think it will make Nation closer to a real nation.

**Comment by Arckenver** [comment]
This is a good idea to put some roleplay into the plugin.

Unfortunately, I'm afraid it is a bit too specific, and many servers wouldn't like that kind of jail system in the plugin. However, the idea of players being granted the right to kill others could be usable.

**Comment by 5igm** [comment]
Thank you very much.

**Comment by TheoKah** [comment]
I do not think granting players a unilateral kill permission would be a good idea. I'd rather say one must use the PVP flag (either in nation or in zone), this way would be fair.

Otherwise I can see abuses like tricking someone into a nation (like a "tp for free diamonds" message in chat) and kill him giving him no chance to defend.

**Comment by 5igm** [comment]
I think GM can publish the related rules to stop these things happening. I think if the function, president endows certain players to kill and put the player into nation's jail, has an independent permission, it will be the solution for the bully. GM can only grant this permission to some credible presidents. If the player who played police officer abuses normal players, the innocents can ask help from the presidents or officers. If the abuse made by the president, GM can cancel the president's permission.

**Comment by 5igm** [comment]
Compared with the benefit in entertainment, I think the weakness can be ignored. If the server owner dislikes this system, actually they can just don't give the permission to any president.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
