### ISSUE TITLE
[Bug] Changing flags in Virtual Nations

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#120]
When changing flags in Virtual Nations it actually changes the flag of the nation you're currently in, I suggest adding an Admin version of `/n flag` - `/na flag <nation> <flag> <true/false>`

**Comment by TheoKah** [comment]
I think you are talking about the actions when someone is clicking the chat message you get with /n here ?

Because `/na flag <nation> <flag> <true|false>` already exists

**Comment by yepidoodles** [comment]
Yeah I guess I derped and missed the a in the command, but still applies for the clickables in `/n info <nation>` 
If you're in 2 Nations, it changes the setting in the wrong nation and if you're not in the nation it doesn't work at all with all the permissions - I guess it's not a big deal as the command works but would still be nice to have work properly.

**Comment by TheoKah** [comment]
You are not supposed to be in 2 nations... At least the plugin do not expect you to be...
Why do you need it?

**Comment by yepidoodles** [comment]
Well it's possible to be in 2 at once as an Admin command can do it, I discovered it as I was in both a personal and a Virtual Nation at the same time.

It's not really an issue for most people, but it would be nice to have fixed.

**Comment by TheoKah** [comment]
You do not need to be in an admin nation to manage it.

Keeping this issue open as a reminder to change the onClick action for admin nations to /na

**Comment by TheoKah** [comment]
onClick actions will be fixed in v2.5 (release in a few minutes)
