### ISSUE TITLE
[Request] Show nearby Nations

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#122]
As you can not build within x amount of blocks between Nations, it would be helpful to allow players to do a command which tells them how close/far those Nations are.

Perhaps `/n close`

Show's the Nation's name, the closest co-ordinate and the direction from your position.

**Comment by TheoKah** [comment]
As of v2.5 when trying to claim land too close from another nation, the name of the conflicting nation appears in console with it's coordinates.

I'm not sure I want to allow players to know which nation is in the way.

**Comment by yepidoodles** [comment]
Why does it matter? They'll still be able to find it if they look.

**Comment by TheoKah** [comment]
Depends the distance actually.

I can add `/n close` and will be able to use its perm node if we want to block it for users
