### ISSUE TITLE
False no permission spam

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#124]
Several of my players have been reporting that they have been getting 'You don't have permission to build here' spam when they are in claims that are theirs and they aren't even interacting with anything.

I believe it's due to Forge's '[fakePlayer](https://takahikokawasaki.github.io/minecraft-resources/javadoc/forge/1.8-11.14.1.1320/net/minecraftforge/common/util/FakePlayer.html)' but I can't know for sure, I currently have a player whom is getting the message several times a second and I can't find the source.

Nation file:

https://pastebin.com/bVAsCjKk

**Comment by yepidoodles** [comment]
Wiping their player file seemed to fix the issue, not sure why.

**Comment by TheoKah** [comment]
I think this might be a machine from a mod that tried to break/place blocks using the players' uuid.

Reseting their data made the mod faillover to another uuid and stop spamming the player.

IMO this is a normal behaviour.
