### ISSUE TITLE
"Too close to another nation"

### ISSUE THREAD

**Issue by Evorss** [Arckenver/Nations#127]
Everything was working great, but after creating 2 nations there now is a bug that if you don't go aprox. 10'000 blocks away from the nation you can't create a new one, I checked the config and I had set the minimal nations distance to 20.

**Comment by yepidoodles** [comment]
Could you post a copy of the config?

**Comment by Evorss** [comment]
https://pastebin.com/KG79E2ku

**Comment by yepidoodles** [comment]
I assume you tried restarting the server and resetting the config?

**Comment by TheoKah** [comment]
What version of nation are you on?

**Comment by Evorss** [comment]
Sorry for the late answer, I deleted the config, restarted the server and I still have the same problem.
I'm on nations 2.4

**Comment by yepidoodles** [comment]
Version of Sponge?

**Comment by Evorss** [comment]
SpongeForge: 1.10.2-2281-5.2.0-BETA-2274

**Comment by yepidoodles** [comment]
I'm using the exact versions as you and not seeing this issue... Using Forge 2281 I assume?

**Comment by Evorss** [comment]
No it runs 2254.

**Comment by yepidoodles** [comment]
Try updating to 2281, Sponge is designed to work on specific versions of Forge, not using the same version can cause issues. I doubt it's causing your issue, but it's worth a try at this point.

**Comment by Evorss** [comment]
Ok thanks, I'll try it right now.

**Comment by Evorss** [comment]
Still get the same problem with the default config.

**Comment by TheoKah** [comment]
I though I fixed the problem prior 2.4 but nope

Use this version and should be good:
[Nations-2.4.jar.zip](https://github.com/Arckenver/Nations/files/974015/Nations-2.4.jar.zip)

I'll work on 2.5 asap, hopefully next week
