### ISSUE TITLE
[Suggestion] Dynmap

### ISSUE THREAD

**Issue by BreeOge** [Arckenver/Nations#128]
Would be awesome if we could get Dynmap integration!

Thank you

**Comment by yepidoodles** [comment]
There's still a lot of stuff to be fixed and improved on the plugin, this will be very low in priority.

**Comment by TheoKah** [comment]
This will be very low priority indeed. Still a nice feature.
I'll see what can be done.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
