### ISSUE TITLE
The question for the formal release

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#13]
Hi, Arckenver. This is just a little question not bug feedback or suggestion. Have you made a plan for Nation of Sponge API 5.x.x? I am just very curious, because I expect the appearence of the formal release of Nation with full my attention. I have noticed that Spongepowered had stopped the update for MC 1.9.4 which also used Sponge API 5.x.x. Have you considered to release Nation formally based on MC 1.9.4 at first?

**Comment by Arckenver** [comment]
Hi, and thanks for your interest in Nations.

All versions 0.x of Nations will be considered pre-releases and will target SpongeAPI v4.x.x.
When version 5.x.x of the API will be more stable (not `Bleeding` anymore, but `Snapshot` or `Release`, see [here](https://repo.spongepowered.org/maven/org/spongepowered/spongeapi/?)), I'll update Nations to v1.0 (MC 1.8.9 / API 4.x.x) and to v2.0 (MC 1.10.2 / API 5.x.x) at the same time. This will mean Nations will be officially released. Note that on the long term, v1.0 will only receive bug fixes.

Concerning minecraft 1.9, as you've pointed out, Sponge has dropped 1.9.4 support. But if you still want to use it, you'll have to use v2.0 for MC 1.10.2 as it uses API 5.x.x

Don't hesitate to ask if I'm not clear on something.

**Comment by 5igm** [comment]
Thank you Arckenver. I ignored the information from SpongeAPI page. Now, I have understanded. Thanks for your explaination.
