### ISSUE TITLE
[Bug] Minimum Distance Config Resetting

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#130]
It's happened 3 times now, using several different versions of SpongeForge and Forge (But all 1.10.2), but with Nations 2.4. It seems random as to when it happens.

- Alice

**Comment by TheoKah** [comment]
You sure you did not change the config folder location in sponge config?

**Comment by yepidoodles** [comment]
Very sure, haven't touched it.

**Comment by yepidoodles** [comment]
None of my other settings change.

**Comment by TheoKah** [comment]
This should be fixed in v2.5
