### ISSUE TITLE
Set the upkeep period?

### ISSUE THREAD

**Issue by Evorss** [Arckenver/Nations#131]
How long is the default upkeep period and is there a way to change it?

**Comment by yepidoodles** [comment]
I don't know how long it is (I don't use upkeep, I think it's stupid), but there is no way to set it currently.

**Comment by TheoKah** [comment]
ATM the upkeep triggers every 24h, at midday (server time)

I can add a couple lines in the config to set the period.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
