### ISSUE TITLE
[Bug] Editting signs

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#133]
As you're probably aware, you can edit signs if you have Quark installed, Nations does protect against the sign editting, however it still opens the sign to edit it before quickly exiting and giving the no permission msg. In this moment, you can easily delete or add a character or 2.

**Comment by TheoKah** [comment]
It's been fixed with this commit: https://github.com/Arckenver/Nations/commit/d3efde5a5908e8fc212608c2508ab565a10d75c3

But I haven't released it yet. you can use the version I linked in issue #127 which is compiled against the current files on github
