### ISSUE TITLE
API 6 or 7 support?

### ISSUE THREAD

**Issue by StargateMC** [Arckenver/Nations#134]
Hi Mate, When do you think you'll be able to organise API 6 / 7 support? or no plans to update?

**Comment by yepidoodles** [comment]
https://github.com/Arckenver/Nations/pull/123

I believe the dev's are busy atm, probably due to exam season, but I'm sure they will update once they have time again.

**Comment by StargateMC** [comment]
Sweet. Ill use the unofficial build til then.
Happy to help with dev once I get my head around sponge, I'm a bukkit/forge dev.

**Comment by yepidoodles** [comment]
Sweet! I'm sure they'll really appricate having another set of hands!

**Comment by TheoKah** [comment]
Sorry for late update.

Here it is: https://github.com/Arckenver/Nations/releases/tag/v2.8

Note I did not update for last breaking changes in api7 so if you plan on using it on 1.12 check #170
