### ISSUE TITLE
[bug]Zone can not be protected!!!

### ISSUE THREAD

**Issue by le10077** [Arckenver/Nations#135]
Hello, I found your plugin on the ground protection, there are some bugs. Such as water will stay in the protection area, some mod block construction can not be limited.
I'm Chinese.And not good at English.If you don't understand what I mean. Here's a video:
https://youtu.be/QPZDyOSQ4AM

**Comment by yepidoodles** [comment]
I see your point, this could be an issue.

**Comment by TheoKah** [comment]
see #89
