### ISSUE TITLE
Minister can't open chests.

### ISSUE THREAD

**Issue by networkaccess** [Arckenver/Nations#137]
Hey there;
I'm using your plugin on my server, and I created a nation for just me and my younger brother. I promoted him to minister within our nation, and he can do nearly everything I can - that is, except for opening chests. He can open ender chests [but not regular or trapped ones], take items from frames, build and mine, interact with Pixelmon NPCs and more, but he just cannot open regular chests. I've even tried to create zones that he's the owner of, but nothing helps. Support/possible solutions are greatly appreciated!

**Comment by TheoKah** [comment]
Hey. Sorry to hear that

what message error does he gets?
Can he open chests in the wild?

**Comment by networkaccess** [comment]
1) He doesn't get any error messages when he tries to, not even a "you don't have permission".
2) No, he can't.

**Comment by networkaccess** [comment]
Another plugin was causing the issue, but thank you for the help! c:
