### ISSUE TITLE
[Request] Chunk-Claims

### ISSUE THREAD

**Issue by sentork** [Arckenver/Nations#138]
Did you ever think about Chunk Claiming instead of with blocks? Ppl cant realy see where they have claimed something etc. With chunks you can just hit F9 or so

**Comment by TheoKah** [comment]
You can see what you claimed using /n see

I plan to add a config option for admin to choose between chunk and golden axe
(when using a claim command for nation or zone, will auto-select current chunk)

**Comment by sentork** [comment]
oh ok, will be there be a eta on the config option?

**Comment by sentork** [comment]
How far is this plan of yours?

**Comment by TheoKah** [comment]
Hard to say for sure. But this is something I want for my servers too. I think I can have a beta for this feature next week.

**Comment by sentork** [comment]
ok good, im happy to test it too :D

**Comment by sentork** [comment]
Any update on  Chunk Claiming?

**Comment by TheoKah** [comment]
Will be available later today
