### ISSUE TITLE
[Request]Would you mind to add an api?

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#139]
I want to make some plugins which will follow Nations' setting. But There is no api in the Nations. Would you mind to add an api?

**Comment by TheoKah** [comment]
That's something I want to do.
I'll see what can be done

What do you expect from the api?

**Comment by 5igm** [comment]
I want to make an arresting plugin which is planned to make the country more real. Thereby, I want an api which I can get the nations, officers, etc.

**Comment by TheoKah** [comment]
That I can do. I'll see if I have time for Nation next week. There is quite a bit of things I want to do.

**Comment by 5igm** [comment]
Thank you very much.

**Comment by 5igm** [comment]
@TheoKah Furthermore, if it is possible, I also want to link the nations' banks.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
