### ISSUE TITLE
[Request] Nearby Flag

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#140]
Hello,

This request is to create a Nearby flag on Nations to allow other Nations to claim nearby. This will be mostly helpful to allow new players to claim around inactive ones (Usually people who have been offline for +30 days). It would also be cool (not completely necessary) if all of the players in a Nation have been offline for +30 days (configurable) the flag would automaticly change to true.

Thanks!

- Alice Sellars
[DragonTechMC](http://dragontechmc.com)

Btw I have been learning and practicing Java a lot over the last few months, I hope to be able to make pull requests eventually instead of keep asking you to do everything!

**Comment by yepidoodles** [comment]
If this does get added, we may want to move the flags from `/n info`, make a new page for it with a clickable to it on `/n info`

**Comment by TheoKah** [comment]
This is what upkeep is for, auto-expire nations after some time.

I can add a time limit tho. If noone in from the nation connected within N days, nation will auto-drop. (default is disabled)

**Comment by yepidoodles** [comment]
But that would delete the Nation, correct? I don't want to delete them, only let others make new ones nearby. Raiding, griefing and stealing of any kind are completely forbidden on my servers, even for inactive players.

**Comment by TheoKah** [comment]
Then you can play with the min distance I guess.

I can see the point. But I'd like to keep the number of flags to a minimum.
So that would be a no for the flag.
However, I can see if I can add something for ignoring the limit if a nation is inactive for too long.

**Comment by yepidoodles** [comment]
Surely more flags are better? You can always move flags from `/n info` to say... `/n flags` if you're worried about it getting cluttered.
