### ISSUE TITLE
Mod Chisel not supported [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [Arckenver/Nations#141]
Hello
I use your plugin for protection on public servers.
But there are some things that are not protected, for example the mod chisel allows to change the blocks of the constructions and that is a complete disaster.
It would be helpful to solve that.
Regards!

Sponge Forge: 1.10.2-2281-5.2.0-BETA-2379
Nations: Nations-2.4
Chisel: Chisel-MC1.10.2-0.0.10.22 and chiselsandbits-12.12

**Comment by TheoKah** [comment]
I think I know how I can fix that.

I'll probably have time for this tomorrow

**Comment by HeberonYT** [comment]
Thank you for your response, I will be waiting for the update!
Regards!

**Comment by TheoKah** [comment]
I'm about to release v2.5 that should fix this problem
