### ISSUE TITLE
Request for new flags

### ISSUE THREAD

**Issue by HeberonYT** [Arckenver/Nations#143]
Hello!
I have different needs to cover in my public servant and some of them could be solved if it considers timely to add extra flags for the nation.
Here some:
PVE: Enable / Disable damage to animals, enemies and villagers within a nation. This to avoid granting permission to "interact" as it might have permission to open anything else.
Enter: Enable / Disable the entry of foreigners, if disabled, users will not be able to enter the interior of the nation. Only the members of it can enter.

I will be updating this post to mention more flags and configurations.
Regards!

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
