### ISSUE TITLE
Mod not supported [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [Arckenver/Nations#144]
This mob breaks the blocks when walking, no matter if it is protected.
![screenshot_9](https://user-images.githubusercontent.com/13698597/27361611-28e297e4-55ee-11e7-9c6e-d1d5f8a92d22.png)

1.10.2_deadly_monsters_1.5.jar
Nations-2.4.jar
SpongeForge version: 1.10.2-2281-5.2.0-BETA-2379
Forge version: 12.18.3.2281
Java version: 1.8.0_111

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
