### ISSUE TITLE
"Too close to another nation"?

### ISSUE THREAD

**Issue by networkaccess** [Arckenver/Nations#146]
[I know, me again lol].
So nations was working perfectly fine for us, until one day I kept getting a "too close to another nation" error while trying to expand my nation's claim. I thought it was kind of strange, as the server hadn't been released yet, and flying around revealed no other nations [also, this was completely out of the blue. Up until this point I could claim fine]. 
Now, fast forward to when we release the server, and a player is having the exact same issue that the staff had been having for months. There is literally _no_ other nations nearby. Can you help us out?

**Comment by TheoKah** [comment]
Check console when you do this. I print more details about which nation is conflicting.

Also make sure you are using the last version. Similar bug has been fixed already.

**Comment by networkaccess** [comment]
I'm using the most recent version, and nothing seems to appear in console other than people entering/leaving nations.

**Comment by networkaccess** [comment]
Is there a config option to change the minimum distance between nations?

**Comment by TheoKah** [comment]
Oh yes, I'm a derp. See https://github.com/Arckenver/Nations/issues/127

**Comment by TheoKah** [comment]
It has been fixed month ago but I did not release it yet...

**Comment by TheoKah** [comment]
Release incoming
