### ISSUE TITLE
[Suggestion] Admin Nation

### ISSUE THREAD

**Issue by Telmudjin** [Arckenver/Nations#147]
Hi ! Would it be possible to add a new feature to the plugin ?

Would it be possible to ensure that zones of an Admin Nation are not buyable if the player is not a citizen of the nation ? (Like for the "player" nations). Thanks !

**Comment by TheoKah** [comment]
You can do that already. Either not put it up for sell (`/z nfs`) or set the zone flag "public" to false (`/z flag public false`)
