### ISSUE TITLE
An /z expand for the zones?

### ISSUE THREAD

**Issue by Odasio** [Arckenver/Nations#149]
Hi there !

I just have the idea to add the same feature of the nations for the zone, like we can claim other part or a polygonal selection for zone who can't be create in a rectangular shape !

Hope to have a positive answer ! Bye

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
