### ISSUE TITLE
Flag Admin [Suggestion] [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [Arckenver/Nations#150]
It is necessary to create a white list of blocks (ID's) that are allowed to break within protected zones.
This allows users to break their tomb (added by a mod) within Admin zones, such as spawn, lobby, etc.

**Comment by TheoKah** [comment]
Such feature already exist for tomb. It defaults to the gravestone mod, but can be changed in the config

**Comment by HeberonYT** [comment]
I currently have this mod of tombs, but they can not be broken, I guess you mean a different one.
![screenshot_6](https://user-images.githubusercontent.com/13698597/27806247-06011938-5fff-11e7-9dfb-038729373909.png)

**Comment by HeberonYT** [comment]
Reviewing the NBT file, the ID of the tombstone is the same as that assigned in the Nations configuration, but it does not work.
Should I activate something else?
![screenshot_6](https://user-images.githubusercontent.com/13698597/27806330-9a9cd5dc-5fff-11e7-9266-8876bd5a2f5b.png)

**Comment by TheoKah** [comment]
That is wierd...
Do you have a message when trying to break the grave?

Do you allow anyone to break the tombs or just the owner? (In gravestone config)

**Comment by HeberonYT** [comment]
Anyone can break the grave (only_owners_can_break = false)
My config: https://pastebin.com/raw/8FmAXPZm

**Comment by TheoKah** [comment]
Do you have a message in chat when trying to break the grave?

**Comment by HeberonYT** [comment]
No message appears, the image shows the chat and the console during the same time period and nothing is recorded.
![screenshot_6](https://user-images.githubusercontent.com/13698597/27809168-ee2302e0-6012-11e7-9008-34e508d91695.png)

**Comment by TheoKah** [comment]
Then it is probably not Nation.
I'll keep this issue open until we make sure.

Can you post your plugin list?

**Comment by HeberonYT** [comment]
**Plugin list:**
PermissionsEx-Sponge.jar
BuycraftX.jar
holograms-2.2.jar
Nations-2.4.jar
Prism-3.0.0-beta2-45-gfbbeb2b.jar
TotalEconomy-v1.5.3.jar
spongeforge-1.10.2-2281-5.2.0-BETA-2433.jar

I think that if it is related to Nations, otherwise I do not have another mod / plugin that adds protection in that area where the tomb is generated, and also prevents the owner from breaking it.
I hope you can give me an answer as soon as possible, I have a public servant and this is really a problem.
Regards!

**Comment by TheoKah** [comment]
Can you try with the version you can download in the last comment of https://github.com/Arckenver/Nations/issues/127 ?

**Comment by HeberonYT** [comment]
@TheoKah I downloaded it but it does not work. He tells me that I do not have permission to break there.
Please do the test yourself, it looks like the plugin is broken with that version of the gravestone mod.
Regards

Mod version: gravestone-1.5.13.jar

**Comment by TheoKah** [comment]
Oh my bad. I misunderstood.

This config allows the gravestone to SPAWN, not to be broken. (As it appears to be placed by the player killed)

The only way right now to BREAK a tomb is to have permissions on the plot.

I guess I can add a permission flag "can break tomb everywhere"

**Comment by HeberonYT** [comment]
Good day.
Granting the permission to interact is very dangerous, especially when they are public areas such as the lobby or spawn of a server.
I would appreciate if you could add a solution.
Thank you.

**Comment by TheoKah** [comment]
Policy on my servers is 'your grave belong to the plot owner now so ask him'  and 'ask an admin if you die in spawn'. But I see your point. I'll see what I can do

**Comment by HeberonYT** [comment]
That's what I'm doing, but my administrators are not always connected and when they are, there are too many tombs to remove or deliver.
Another common problem is that on my server missions are performed with the CustomNPC mod and therefore players usually leave their tombs in those protected areas making it impossible to access other users who want to perform the mission.

**Comment by HeberonYT** [comment]
**Hello!**
Something new?

**Comment by yepidoodles** [comment]
TheoKah is a busy guy, please be patient.

**Comment by HeberonYT** [comment]
**Hello** @TheoKah , it would also be nice to add the VendingBlock mod identifiers. 
https://minecraft.curseforge.com/projects/vending-block

I usually create public markets on my servers where people place their vending, so everyone does trade in a very nice visual way, I've never liked using safes and signs that are confusing and horrible. In version 1.7.10 I have used WorldGuard to create the spaces where vending will be placed, without allowing users to destroy the entire market.
It would be good if you also added an option where they would allow and block these blocks in the protected nations. You do not have to worry about vending thefts, since the mod only allows the owner to break or remove it.
_Regards!_

**Comment by TheoKah** [comment]
This problem can be handled with this: #118 

We can continue discussion there
