### ISSUE TITLE
Sign Shop Issue with v2.5

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#153]
As you know, I'm using CarrotShop (v1.8), but once I updated to v2.5 no one could use the sign shops anymore (Had to back-date). I'm assuming this is due to the improvement with mod protection (I do have Quark installed, but sign editing is disabled on both client and server).

But otherwise, great job on v2.5, I'm sad I can't actually use it xD

As always, many thanks,

- Alice

**Comment by TheoKah** [comment]
Can you reach me on discord? I'll try to find a moment later this week or during the week end to spot the problem and fix it.

**Comment by TheoKah** [comment]
This happened to be a problem with CarrotShop. I fixed it there: https://github.com/TheoKah/CarrotShop/releases/tag/1.9
