### ISSUE TITLE
Colour issue

### ISSUE THREAD

**Issue by CrazyLewis** [Arckenver/Nations#154]
![2017-07-18_15 47 15 2](https://user-images.githubusercontent.com/30266197/28324387-1fc6d760-6bd3-11e7-94d4-d5062d79edf6.png)

Leaving a nation the colour is okay, But when you walk into a nation the light yellow for ( Leader name ) is hard to see when someone lives in a desert, All the other colour are okay just the light yellow.
If it could get changed to a darker colour that would help a lot, Maybe a dark blue but I will leave that up to you.

Or could you drop a comment saying how I could change it my end so it don't have to be a full update maybe.

Many thanks.

Lewis.

**Comment by TheoKah** [comment]
You can now format the toast in the config: https://github.com/Arckenver/Nations/releases/tag/v2.6
