### ISSUE TITLE
[Request] Claim Blocks for each rank

### ISSUE THREAD

**Issue by SkrillexAkaCraft** [Arckenver/Nations#158]
Anyway to make it so that lets say certain groups can claim more or les blocks than the other groups?

for example:

Default 1000
DonatorGroup1 5000
DonatorGroup2 10000
etc
etc
etc?

**Comment by TheoKah** [comment]
This can be done already using `/na extra` or `/na extraplayer` when giving the perm group.

Now I can make it so the plugin check the perms of the president too for any extras. We can discuss it.

**Comment by SkrillexAkaCraft** [comment]
i was looking into this and all groups have 5000 blocks but i never found the command for lowering/increasing the extra blocks

Edit:
ok i tried /na extraand i found the command :) ty for the info

**Comment by TheoKah** [comment]
Will this command do the trick?

**Comment by SkrillexAkaCraft** [comment]
Will see what i can do :)

https://gyazo.com/26bd76715f15a8173ef73894dacae560


[Edit]
Seems like the user needs to create a nation first before i can do that so nope won't work :/

**Comment by TheoKah** [comment]
You have `/na extraplayer` too.

I can see a use for this. Being able to set extra claims in the perms would be useful. I'll add this feature.

**Comment by SkrillexAkaCraft** [comment]
yeh would be cool to see it in the permission section tho

[Edit]
i mean in the group section 'depending on the players group'

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
