### ISSUE TITLE
[Suggestion] About the flag, use

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#159]
For now, if a player is granted the flag of use as true in a nation, it means he can interact any interactive stuff include buttons on the walls or redstone comparator and daylight detector. This may cause big trouble. I suggest that the plugin allows users to specify what can be interacted, but not like now it is impossible to edit.

**Comment by TheoKah** [comment]
I plan to make it possible. I dont know how yet (probably more flags but I still want to think about it. I want to keep it simple)

**Comment by 5igm** [comment]
Maybe works like Polis?

> /polis allowblock - Polis leaders can use this command then right click any block in
> their claim to toggle the blocks "right-clickability" by members of other teams.

https://forums.spongepowered.org/t/polis-v2-7-0/9732
@TheoKah

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
