### ISSUE TITLE
Flag explosion doesn't work

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#161]
I have set explosion of a nation as false, but it doesn't work. The creeper from outside still can destroy the building. For example, if a creeper explodes in the nation, the building will be safe, but if the creeper explodes out of the nation but near the nation, the building in the nation will still be destroyed.

**Comment by TheoKah** [comment]
I'll see what a I can do about this

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
