### ISSUE TITLE
Is there a config to set the number of zones each citizen can buy in a nation?

### ISSUE THREAD

**Issue by le10077** [Arckenver/Nations#163]
Is there a config to set the number of zones each citizen can buy in a nation?

**Comment by TheoKah** [comment]
There is no hard limit. IIRC towny did not have any limit for plots either at a town level.

On my servers it is up to the president to fix a limit and usually they do that with a sign at nation spawn...

I'm open to discussion.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
