### ISSUE TITLE
API6 Support

### ISSUE THREAD

**Issue by Tencao** [Arckenver/Nations#164]
I'm currently running a sponge 1.11.2 server and running this mod alongside it is spitting out tons of errors that I can only assume is because of the API changes. Is there any plans to release an API6 version of the mod?

**Comment by TheoKah** [comment]
There is. I need to find some time to test it.
I'll see if I can compile a beta tonight

**Comment by ProsperCraft** [comment]
I am running a 1.12 server, would love to help you test.

I am getting some java.lang.NoSuchMethodError errors.

**Comment by ProsperCraft** [comment]
ping

**Comment by TheoKah** [comment]
I've been away this week end. I'll compile a 1.11 and 1.12 version asap for you to test. If working, I'll officially start maintaining multiple branches.

**Comment by kortakai** [comment]
I have it on my 1.12.1 server using API7, and so far it's been working okay besides spamming errors to there and back lol. But people have been able to setspawns, do nations, set permissions that seem to work (minus zombie attacks lol)

**Comment by TheoKah** [comment]
Can you send me a copy of those spamming errors?

**Comment by kortakai** [comment]
https://pastebin.com/d3sMxtMK is where i uploaded it to which should have the right information. If it's missing something (which is possible I hate reading nano sometimes lol) lemme know and I'll dig more :)

**Comment by TheoKah** [comment]
This will help. I should be able to fix all this next week end

**Comment by ProsperCraft** [comment]
Thats really interesting, it doesn't log the errors to the logs, which is good or it would fill the hard drive :)

Here is a snippit from console.l https://gist.github.com/ProsperCraft/4769ff32543bde22d9b8baa3e795c26c

**Comment by ProsperCraft** [comment]
forge-1.12-14.21.1.2443-universal
spongeforge-1.12-2443-7.0.0-BETA-2498

We can't go to sponge 1.12.1 because we are waiting on the pack to update, which is waiting on AE2 to update.

**Comment by kortakai** [comment]
Thanks @TheoKah for looking into this! =)

**Comment by TheoKah** [comment]
Here it is: https://github.com/Arckenver/Nations/releases/tag/v2.7

Let me know how it goes

**Comment by kortakai** [comment]
Just as an update - No spam in the logs, And zombies aren't breaking down doors lol.

**Comment by TheoKah** [comment]
Sooo all good?
