### ISSUE TITLE
Config keeps getting Reset

### ISSUE THREAD

**Issue by sentork** [Arckenver/Nations#165]
Hey, both the language, and the main config get reset after every restart, also the folder is being regenerated. Any clue? i would need a fast fix for this. Thx in advance!

**Comment by TheoKah** [comment]
What version are you using? (Nation and sponge)

Do you turn the server off before making any changes?
If you do it with a live server, you need to `/na reload` before you restart

Edit:
Modifications on the language file must be done with server off, I'll make it possible to reload the language file using `/na reload` as well

**Comment by sentork** [comment]
Tried it with diffrent sponge versions. Removing line 43 in ConfigHandler seem to have fixed it

**Comment by TheoKah** [comment]
Wierd.
Looks like a problem with permissions on your files.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
