### ISSUE TITLE
too many argument

### ISSUE THREAD

**Issue by bombaroberta** [Arckenver/Nations#167]
hi all.
i have dl nation 2.8 and like 2.7 when i put it in my sponge serv no one of all commands work :

https://image.noelshack.com/fichiers/2017/34/3/1503514838-2017-08-23-20-53-23.png
https://image.noelshack.com/fichiers/2017/34/3/1503514836-2017-08-23-20-53-27.png

**Comment by TheoKah** [comment]
Ffs
Is it using a linux or a window server?
Do you have errors in console when loading the server?

You can stick to 2.6 for now

**Comment by bombaroberta** [comment]
it's ok im using 2.6

**Comment by TheoKah** [comment]
You can update now, we found the problem: #171
