### ISSUE TITLE
Unclaiming Issue

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#169]
Unclaiming has stopped working - I'm not sure after which version as it doesn't seem very used, but today we noticed the problem.

If you select an area and use `/n unclaim` or `/na unclaim <nation>`, it says that it successfully unclaimed, but the selected area is still claimed.

Nations Version 2.8 for 1.10.2
SpongeForge: 5.2.0-BETA-2610

**Comment by TheoKah** [comment]
What mode are you on?
chunk based or golden-axe based?

**Comment by yepidoodles** [comment]
Golden axe (Sorry, forgot about the chunk claims)

**Comment by TheoKah** [comment]
I tried a few things, the only non-working unclaimed pattern is when trying to unclaim a rectangle that is fully inside a nation's, not touching the borders. Like when you try to make a hole in the nation.

Do you see the same problem? Any other patterns not working?

If that's the only one not working, I'll leave it unfixed for now as a quick-fix could break the claiming

**Comment by yepidoodles** [comment]
Yes, it appears to only be that one (inside a claim) that doesn't seem to work (I don't know why I didn't think to check the others or mention that, I'm being such a derp lately). More than happy to wait, just wanted to make sure it was reported :)
