### ISSUE TITLE
Financial system

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#17]
I have a great idea for nation bank system, but it might be a little complex.
If national bank can  "get players' fixed time deposit and pay back players with interests",  "loan money to citizen", "set taxes rate according to players' account deposit", I think it will be an amazing improment. 
## Get players' fixed time deposit and pay back players with interests

Now, nation bank actually is only a storage of money. Its majority deposit comes from president's contribution and taxes.  Sometimes, if the nation needs a lot of money like claiming lands, it needs a lot of money. In addition, currently for paying Upkeep,  most countries have to set taxes equal or higher than Upkeep (because president and ministers don't pay taxes). Actually high taxes will make players being disgusted with nation system. But, it is impossible to cancel Upkeep as well, because it plays an important role to server economy.

> **The use of Upkeep**
> For example, in my server, server will pay players money according to their online time. According to this setting, the total amount of money will be incredible high soon. Yet, if there is a way used to take these money back to the server, the problem will be solved. I think some servers give players money by buying players' items. If there is not a useful recycle system, these servers will face the same issue certainly.

Compared with increasing taxes, there is a better way to support a country's finance - attracting people to deposit their money in national bank. Actually, this method's  transformation is taken by most countries in reality. If the bank  want to attract people to deposit, it have to  add a function to pay users interests. 
## loan money to citizen

This function is a supplement to player deposit. For the bank, it can use users' deposit to support countries' construction, but actually its money is borrowed from players. The money is not belong to nation or bank. To avoid bank system changing to a financial swindling, I think it is necessary to allow nation banks to loan money to citizen. It will be a supplement to the cost of country.
## set taxes rate according to players' account deposit

This is a important source to country's finance. In fact, it is like progressive tax rate. It owns two priorities:
1. balancing the power of new player and old player.
2. benefit nation's economy.

**Comment by 5igm** [comment]
Actually, I think for current version, managing system in nation is closer to hamlet or village not a country. I think more advanced financial system will make it be closer to a real nation.

**Comment by Arckenver** [comment]
This is a very interesting suggestion. However, introducing such a system would be quite complicated and a lot of things will have to be done in order for it to work, that's why I keep it in mind but give it a low priority for now. It's also for people to come and discuss this system on this issue.

## Interests

Interesting, but isn't it like just reducing the taxes ? Wouldn't it be bad for the nations to have less income ?

## Loans

In practice, I guess this should be managed by the nation's staff. I mean that they should decide how much the nation can lend, isn't it ?

Also we need to be sure the player will return back the money. So we'll have to handle some cases like if the player leaves the server forever.

## Relative taxes

That's indeed a good idea here. I guess you imagine something like a percentage of the money the player has ?

**Comment by 5igm** [comment]
@Arckenver I am very happy to hear these feachers will be achieved in the future although they are in low priority. I trust it will make Nation being more unique and attractive. 

Interests
For interest system and other complicated systems, I think they should base on level system. It means only nation with high levels can use them. For newbies, it is obvious that they don't have enough experience to deal with these features. For veteran, I also believe these features should be the necessary requirement for them to the next level. I think, like real nation, if a country can use thses financial tools correctly, it is impossible to make nation losing money.

Loans
Yes. I totally agrea with you.

Relative taxes
In real world, Tax Bureau decides taxes according to people's income. In minecraft world, it is impossible, because actually there is no job. I think maybe Nation should give this power to a nation owner to decide the taxes for his/her citizen. I think total deposit and total online time will be important for a nation owner to decide taxes.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
