### ISSUE TITLE
[1.12.1] Console startup error

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#170]
Hello!

Today we started setting up a testing 1.12.1 server and got an error using corresponding 2.8 version of Nations.

For some very odd reason, my `fml-server-latest` logs all end at line 3046... I honestly have no idea why, so I can't get the error in text form, so I just took a couple screenshots.

https://imgur.com/a/tPNeH

EDIT: Using spongeforge-1.12.1-2480-7.0.0-BETA-2629 (forgot to add that)

**Comment by TheoKah** [comment]
They changed a lot of things in the 1.12 api recently. I need to update to take that into account

**Comment by TheoKah** [comment]
Here is a quick-fix:

[Nations-2.8-S7.0-MC1.12.1.jar.zip](https://github.com/Arckenver/Nations/files/1309077/Nations-2.8-S7.0-MC1.12.1.jar.zip)

Let me know how it goes.
You want to extra check spawning of items (drop / break blocks in claimed areas...)
