### ISSUE TITLE
too many arguments 

### ISSUE THREAD

**Issue by pyscho974** [Arckenver/Nations#171]
when running nations  i get a message too many arguments anytime i use the /n create and seems various other commands as well. not sure why this is. 
running luckperms i set all the permissions they seem to work yet when you run a command it gives the too many arguments line  everytime. using economylite and that plugin works. figure either a bug or im missing something obvious and just not seeing it.

**Comment by TheoKah** [comment]
If you want to put a space in a nation name, use an underscore ( _ ) instead

**Comment by pyscho974** [comment]
was typing "/n create town"  got to many arguments. even "/n claim" says to many arguments.. nearly all the nations commands do this .

too many arguments
town
^
usage: /n

**Comment by yepidoodles** [comment]
Which versions of Minecraft, Sponge and Nations are you using?

**Comment by pyscho974** [comment]
newest versions for 1.10.2 modded space astronomy 2

Nations-2.8-S5.1-MC1.10.2.jar
spongeforge-1.10.2-2477-5.2.0-BETA-2637.jar
forge-1.10.2-12.18.3.2477-universal.jar

its a public server we just not advertised this one yet

**Comment by yepidoodles** [comment]
I'm a few versions of SpongeForge behind you, I'll update and see if I get the same issue.

EDIT: Updated - Can not reproduce. 

Might want to check to see if another plugin might be interfering.

**Comment by pyscho974** [comment]
hmm only other plugins is luckperms, economylite and nucleus. .. does adding it after world creation change how it starts up?

**Comment by TheoKah** [comment]
Are you using a linux based server or a windows one?

**Comment by pyscho974** [comment]
windows server 2008r2

**Comment by TheoKah** [comment]
This is why

Can you load this version and send me the log ?
This won't fix the problem but it will help

[edited out]

**Comment by pyscho974** [comment]
yep.. have to give me a bit to reload it all.. have couple people in server with me at moment

**Comment by pyscho974** [comment]
having issue trying to get the server log to you.

**Comment by TheoKah** [comment]
Can you give me the output of `java -version` in the meantime ?

**Comment by pyscho974** [comment]
mean like the first 50 lines of it?.. is there a chat system byou use? 
[edited out]

hope that helps. wasnt my first choice of things to send log file to you tho.

**Comment by TheoKah** [comment]
no, I mean the version of java you are running on the machine.

From a command line (if you have a GUI: Windows+R -> "cmd" <enter>)

In the meantime, here is a blind-fix of a possible problem one can have with window's path... This might fix your problem, might not... I'd still need the output of the console (just the lines about nation)

[edited out]

**Comment by pyscho974** [comment]
yeah big log file for something we just restarted little bit ago.. ill test this blind fix out see how it does tho.

**Comment by pyscho974** [comment]
sorry for a long delay on replies..  was copying files from the server download to my desktop. same error.. tho /nw does work.. till i type /nw info then says to many arguments with the blind fix in place.  im  not 100% sure what lines of info you need out of the log files tho. ill see what i can dig up tho

**Comment by pyscho974** [comment]
went threw logs.. got all instances of nations with in it.. did not see any conflict areas.

[edited out]
hope it helps

java ver.  jre-8u144-windows-x64

**Comment by TheoKah** [comment]
The pastebin gives me a 404
About the log, I just need the console output about nations

**Comment by pyscho974** [comment]
odd it come up 404 with me to but said github not pastebin .  if that information is entered into the browser it works tho.

**Comment by TheoKah** [comment]
Odd indeed.

Ok so I think the problem comes from the spaces in the name of some of the folders your server is on.

I'll send you a new jar when I'm home

**Comment by pyscho974** [comment]
sorry this has become such a issue for you to work on. 

ok.. yepidoodle explained to me what you meant by spaces..  makes me feel like a idiot to not think that was a issue lol..

**Comment by TheoKah** [comment]
This is an issue, but this is not a reason for the plugin to fail loading commands.
I'll make it so it can load them regardless of the spaces in the name.

**Comment by pyscho974** [comment]
is strange that  the spaces in the name stopped it from working tho.. id have never guessed that as an issue.

**Comment by TheoKah** [comment]
Reason is starting on 2.7, I'm loading the classes for commands dynamically. To do this I analyse the plugin's jar. To do this, I need its path. And I get a path with '%20' where spaces should be.

**Comment by pyscho974** [comment]
well that i understand.  dont seem like its to complicated a fix then

**Comment by TheoKah** [comment]
If this is the problem then no. I'll fix if in an hour or two

**Comment by pyscho974** [comment]
well i tested on my desktop by changing the name of folder from "space astronomy 2" to "sa2" and it works now. im  just glad we found the problem. by myself i would never guessed those spaces in the file name would done that much to stop it from reading the commands in game or threw the cmd window. i really do appreciate you taking the time to help figure the issue out.

**Comment by TheoKah** [comment]
Here it is with a clean version that handles spaces in path correctly:

[Nations-2.9-S5.1-MC1.10.2-hotfix_windows.jar.zip](https://github.com/Arckenver/Nations/files/1345362/Nations-2.9-S5.1-MC1.10.2-hotfix_windows.jar.zip)

I won't tag a new release as there is nothing new.

**Comment by pyscho974** [comment]
seems to work great.. thankyou.
