### ISSUE TITLE
[request] flag world and interaction wilderness

### ISSUE THREAD

**Issue by bombaroberta** [Arckenver/Nations#172]
Hi 
Is it possible to add in flag, a part to disable command like /fly and other because when we use nation we need to use an other plugin for flag region but the server doesn't like it.
And is it possible to allow interaction with golden axe because when you disable interaction in wilderness leader can't claim and allow interaction just for golden axe will fix the problem.

have a nice day and I hope you can add it in your beautiful plugin.

**Comment by TheoKah** [comment]
The golden axe interaction will be fixed in next release (in a few hours)

About the fly command, I'll need to think of it.

**Comment by bombaroberta** [comment]
ok thx you do a real good job.

**Comment by bombaroberta** [comment]
your system of whitelist is awesome just one thing he spam hard the console

**Comment by bombaroberta** [comment]
is it possible to consider to add a way to see the last the connection, numbers of block owned and other information for leader and minister?

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
