### ISSUE TITLE
idea suggestion

### ISSUE THREAD

**Issue by pyscho974** [Arckenver/Nations#173]
admin nations can have zones..  seems is no way to tax people that buy them to use for shops. 
so they sell goods to players and have zero cost for the usage of property.

is this possible? or did i just over look a setting.

**Comment by TheoKah** [comment]
I'll work on that.
I'll make it possible to fine tune upkeep and taxes in 2.11

**Comment by pyscho974** [comment]
there a 2.10 version i didnt see?.. 
thankyou for taking the time to work on that..  im sure it cant be easy to just drop and do coding. tho have seen some genius types that can do the code in their heads before they enter it lol.

**Comment by pyscho974** [comment]
hope im not wrong in asking about a progress update to this suggestion.  just curious on a time frame tho.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
