### ISSUE TITLE
[Request] Separate Chest Interactions

### ISSUE THREAD

**Issue by CamGenius** [Arckenver/Nations#174]
Can you add a separate interaction like use accommodations. For instance beds, chest, enderchest, and animals. Then have another interaction for redstone and trapped chest. I have a lot of users wishing to protect their stuff but still want to set some traps.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
