### ISSUE TITLE
Rent out zones

### ISSUE THREAD

**Issue by tenten8401** [Arckenver/Nations#175]
Title says it all. I think it'd be neato to be able to rent out zones (say for player operated shops at spawn, something like AreaShop). Another cool feature of that would be the ability to save the zones as a worldedit schematic and restore them when the rent is up, but should only be enabled for admin claims.

**Comment by yepidoodles** [comment]
The developers aren't currently looking to add new features I'm afraid, but #173 can cover the rent thing.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
