### ISSUE TITLE
config isnt saved on restart

### ISSUE THREAD

**Issue by ghost** [Arckenver/Nations#176]
spongeforge-1.12.2-2503-7.0.0-BETA-2706.jar

Nations-2.8-S7.0-MC1.12.1.jar as well with the hotfix version of 1.12

mc version 1.12

**Comment by TheoKah** [comment]
If you modify the config file, make sure you '/na reload' before you restart

**Comment by ghost** [comment]
ahh oke couldnt find that anyhere but thanks

**Comment by ghost** [comment]
that did it thanks

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
