### ISSUE TITLE
Issue with Taxes

### ISSUE THREAD

**Issue by Cleardragonf** [Arckenver/Nations#178]
There's an issue when Nations attempted to run the taxes and such for a nation...i'm on:

Forge: 1.12.2-14.23.1.2558
SpongeForge: spongeforge-1.12.2-2529-7.0.0-BETA-2748
Minecraft: 1.12.2

Here's the log
https://www.dropbox.com/s/fspr1uly21ovjd1/New%20Text%20Document.txt?dl=0

**Comment by treyzania** [comment]
Made a Gist of it for convenience: https://gist.github.com/treyzania/45aab64dfaa31ff8eef5c61f7b990930

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
