### ISSUE TITLE
Could not pass DropItemEvent$Destruct$Impl to Plugin{id=nations

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#179]
https://gist.github.com/ProsperCraft/89e95a8a5bc826e0acf2658adfaffa9f

Sponge - spongeforge-1.12.2-2611-7.1.0-BETA-2931
Nations- Nations-2.9-S7.0-MC1.12.1-hotfix1

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/ec07580a12529024052e62f8d21a00d1

Again when a staff member did /kill on himself.

**Comment by pfigueiredo** [comment]
Also have this problem in most commands and at startup: [Server thread/ERROR] [Sponge]: Could not pass FMLServerStartedEvent to Plugin{id=nations, name=Nations, version=2.8-S6.1-MC1.11.2

SpongeForge api 7  (spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar)

**Comment by TheoKah** [comment]
pfigueiredo you are not using the correct version.
You are using the API 6 version of the plugin with API 7 version of sponge

ProsperCraft I guess they changed something in API 7. I'll see if I can fix it. Looks like it is a benign error that should not compromise protection.

**Comment by pfigueiredo** [comment]
Ok cool, did I miss the version 7 downloads? can you point me to that?
I don't see a reference to the api version on this page:
https://github.com/Arckenver/Nations/releases

I do see the S6.1 in the file name.  lets try to find a S7

**Comment by pfigueiredo** [comment]
OK i see. my mistake I got confused with the MC version. is nations only compatible with MC 1.12.1? can I use this version (**Nations-2.9-S7.0-MC1.12.1-hotfix1.jar**) with MC1.12.2?

**Comment by TheoKah** [comment]
Yes you can

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
