### ISSUE TITLE
 problem / n setspawn (name) does not work

### ISSUE THREAD

**Issue by mathcover** [Arckenver/Nations#180]
everything is said in the topic name, I use spongeforge 1.12.2
here is my mistake : https://hastebin.com/abelixedec.vbs
thank you Google Translate

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
