### ISSUE TITLE
Nations  2.9-S7.0 Console spam when users move between zones

### ISSUE THREAD

**Issue by Ryuhouji** [Arckenver/Nations#181]
Hi there. I've to nations installed on my server, and whenever I walk between my zones I get the following spam in the console: https://gist.github.com/Ryuhouji/58e2e4bf838a50c08b797bcdb2a28b0d
The zones I'm walking between are public nation walkways and square zones that are up for sale. It doesn't show 'for sale' or a price for these zones, and I'm not sure if this is the normal behavior or not.

Additionally, this: https://gist.github.com/Ryuhouji/73e3d0b2a5522a2cbc7e0a080cc770bc is shown seemingly randomly, with no apparent cause that I can think of.

I'd like to resolve this, if possible.

**Comment by ProsperCraft** [comment]
We are having this same issue - 
https://gist.github.com/ProsperCraft/9aa8cd05122f0dd4048348a9f87741b7

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-ee6579e
    SpongeForge: 1.12.2-2611-7.1.0-BETA-2996
    Minecraft Forge: 14.23.2.2627

Nations-2.9-S7.0-MC1.12.1-hotfix1

**Comment by ProsperCraft** [comment]
Where is what it looks like in game.

https://gyazo.com/012f4defe0d4ef1961a310e84ec25c80

**Comment by ProsperCraft** [comment]
When this happens, you can't place water blocks and have them flow, you can't make replenishing water supplies, and you can't use block placers to place blocks or they disappear.

**Comment by ProsperCraft** [comment]
@Ryuhouji Please change the topic, its not when they move between zones, you can be standing still, and it just ruins the whole user experience.  Players also get you don't have permission to build spam.

![brokenations](https://user-images.githubusercontent.com/4427684/38712631-30c9dfa0-3e8a-11e8-9dfc-944fc5648724.png)

**Comment by yepidoodles** [comment]
I don't know if you are aware, but the developer who was working on this isn't anymore, and the owner hasn't been active in well over a year. I suggest switching to another claim plugin next time you reset your map.

**Comment by ProsperCraft** [comment]
Griefprevention is super active but doesn't provide us with the economic structure that we need, like residents paying rent, and a price for making a town, and claiming land.  We will just have to recruit someone to help update it if he doesn't pop back in and help.

**Comment by Ryuhouji** [comment]
For us, It was when moving between the zones. It stopped if no one was moving at all.
Additionally, that message looks like a GP configuration error, or Universeguard. Same issue in both cases, you have the entry-deny flag set to true.

**Comment by yepidoodles** [comment]
Grief Prevention comes with an API, so it's possible to get someone to make an addon for it for more town support. But I must say that since switching I have missed Nations (Other than the many problems which never got solved). In any case, good luck.

**Comment by ProsperCraft** [comment]
I wonder if this will help.

I logged out, and it is still spamming about me-

https://gist.github.com/ProsperCraft/69dd717b264e613e261eef8fefde980a

Then when another player logged in - there was  a stacktrace and it and then it switched to them.

It is always the last player to log in.

https://gist.github.com/ProsperCraft/250deaad2a822847056e19b2e0b9ac00

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
