### ISSUE TITLE
/na spy spies on your own nation so you see the chat twice.

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#182]
Please set it so that /na spy doesn't spy on your own nation.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
