### ISSUE TITLE
Wars?

### ISSUE THREAD

**Issue by ACPenguin** [Arckenver/Nations#183]
Could you add something like towny war?

**Comment by EnvyEnfys** [comment]
That would be a really good thing to add.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
