### ISSUE TITLE
Zone Creation, Recognizing Y Coordinates  

### ISSUE THREAD

**Issue by spruill7716** [Arckenver/Nations#185]
Offer as a suggestion:

When creating a zone, the plugin should have the option to allow the recognition of a Y coordinate. I'm trying to configure zones within a multi-story tower to offer to sell to players however only the X and Z coordinates are shown. This makes it difficult to for admins that are trying to sell zones that are individual stories.

**Comment by treyzania** [comment]
IIRC this isn't possible, as regions only store X/Z coordinate for definings rects.  It could be possible, but you'd need to rewrite quite a bit of code to make it happen.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
