### ISSUE TITLE
What version should we be using?

### ISSUE THREAD

**Issue by Routhinator** [Arckenver/Nations#188]
The latest release on Ore is 2.6 but latest release here is 2.9.

Is 2.9 still in testing? Or has Ore just not been updated in nearly a year?

**Comment by TheoKah** [comment]
Ore is outdated.

I'd advice using 2.11 https://github.com/Arckenver/Nations/releases/tag/v2.11_api7

I'll see if I can update ore too but I have little time for this project atm
