### ISSUE TITLE
Pieconomy Compatibility?

### ISSUE THREAD

**Issue by Artres** [Arckenver/Nations#189]
Hey there.
  I'm getting an error when I try to setup a non-admin nation with the Pieconomy Plugin that I use for an item economy.
 'Could not create nation's account, please contact a server administator'
As I am a server administrator, I took a look at the log and all it says is:
 '[Server thread/ERROR] [nations]: Could not create nation's account on the economy service !'

I want to get the nation account working for taxes and things but I'm not sure what the problem is and how to fix it, so I've brought it here under the understanding that it may be a bug or just incompatible at this point.

All help appreciated. Thanks in advance.

**Comment by TheoKah** [comment]
From what I read. Pieconomy supports virtual accounts.
Have you setup that correctly?

**Comment by Artres** [comment]
*facepalm* 

Yeah. For anyone else reading this, there seems to be something that isn't on by default in the config known as dynamic-accounts for Pieconomy that you have to set to 'true'. 

Anyhow, I've just gotten a new error when trying to create a new nation, so the issues continue...

Stack Trace: https://pastebin.com/rkcTcqSH

Sorry for being a pain here. All help appreciated as before.

**Comment by TheoKah** [comment]
```
flavor.pie.pieconomy.runtime.kotlin.UninitializedPropertyAccessException: lateinit property currencies has not been initialized
```
This would be an error for PieEconomy.
If I had to guess, I'd say you did not set a default currency

**Comment by Artres** [comment]
I can confirm that it is set-up. No errors occur in-game besides for when trying to create a nation, I've tested all Pieconomy commands and followed the documentation for setting up the plugin's config.

Update: It seems this the only open issue on the Pieconomy plugin's GitHub issues section is about this, so it's not just me. I'll move over to there accordingly since it seems to be a problem with that plugin but if you have any further help you could offer, I would happily accept.

For those reading this in future and are having similar problems, the issue link is: https://github.com/pie-flavor/Pieconomy/issues/9

**Comment by Artres** [comment]
Fixed on Pieconomy end. Re-download new build, otherwise if it hasn't been released yet, download build from issue link above.
