### ISSUE TITLE
How can I claim lands for admin nation?

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#19]
After I used the command "/na create xxx" to create a nation, I faced a problem. How can I claim lands for it? I am not the president of admin nation.

**Comment by Arckenver** [comment]
You can use `/na claim <nation>` _(N.B. also works with non-admin nations)_

That command was forgotten in the [wiki](https://github.com/Arckenver/Nations/wiki/Commands#nationadmin). I've just fixed it.
