### ISSUE TITLE
Disable /n create to group

### ISSUE THREAD

**Issue by ghost** [Arckenver/Nations#190]
hi, i would like to disable /n create permission for one group and when i give Chief group, they can do /n create.
I don' understand how can i do, can you help me ?

Sorry my english is verry bad ( i'm french )

**Comment by TheoKah** [comment]
You should set the following perms / tu dois utiliser les permissions suivantes:

default group:
- `nations.command.nation` = `true`
- `nations.command.nation.create` = `false`

chief group:
- inherit `default group` or set `nations.command.nation` = `true`
- `nations.command.nation.create` = `true`

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
