### ISSUE TITLE
Some Bugs (and Insects)

### ISSUE THREAD

**Issue by Artres** [Arckenver/Nations#191]
Hey there again,
   Sorry to bother you again, just got some likely bugs over here that I think I should post up here.

Section/Bug 1)
First problem is most likely to be a bug. It was mentioned here a few months ago - https://github.com/Arckenver/Nations/issues/180, but the person who posted it didn't seem to properly provide a log or much in terms of details.

/n setspawn doesn't seem to function, and puts out an error both in-game and in the logs.

Stacktrace: https://pastebin.com/VmeGSmi2
Image of In-Game Error: https://imgur.com/a/Ef7IFLR

Section/Bug 2)
Now we're getting into shaky territory. The deposit command doesn't seem to work properly. It doesn't properly add any deposited amount to the national account despite giving a green confirmation. /n info confirms that no money has gone in despite giving the confirmations. 

No error is created here in the server logs nor games however.

Image of In-Game Confirmation: https://imgur.com/a/bmVNC2s

Section/Bug 3)
This one is as shaky as it can get as it might be linked to Section/Bug 2 and how the plugin works but when trying to use /n buyextra [amount], it just says that there isn't enough gold no matter what amount you have in your inventory. I do understand that this might be because it only takes from a nations' treasury but still thought I'd mention it whilst I was here.

Image of In-Game Confirmation and Error: https://imgur.com/a/J12sCCU

Thank you for taking your time to read this. If you can provide some aid, then great. If you can't, then thanks anyway and at least this is up for future reference.

**Comment by Artres** [comment]
Whilst I have you here by the way, is there a way to disable nation's chat formatting since I have some prefixes and suffixes that it seems to be overwriting from LuckPerms via Nucleus. I know this is a lot. Plz don't hurt me

**Comment by Artres** [comment]
I had some spare time and tried testing some things out and realized that the admin commands allow you to set a nation's 'money'. So I create a nation and ran the command /na eco set Land 1000 (or Nation Admin set the economy/money of Land to 1000). It gave out a green 'Success !' and then when I tried /n info it came out as 'Money: 0 G'. I think the money system is broken or something unless the admin command just doesn't work either.

Screenshot: https://imgur.com/a/A9N68bH

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
