### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Drimmar** [Arckenver/Nations#192]
Well, nations does not support the Russian language. I would like to fix this.
After the translation in "language.cofn" the file "config.conf" becomes empty and the plugin stops workingg.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
