### ISSUE TITLE
Not an issue - How to get prefixes to work?

### ISSUE THREAD

**Issue by BrandHyde** [Arckenver/Nations#193]
On sponge 7 1.12.2, what chat manager plugins offer the ability to display the prefix? Thanks

**Comment by TheoKah** [comment]
I'd say luckperms as this is more or less the only pne still maintained

**Comment by TheoKah** [comment]
And thats it. You can set prefix in messages format in nation's config

**Comment by BrandHyde** [comment]
I've tried all this mate, if you have discord could we kindly discuss? I'm very stuck :) `actualbrand#0001`

**Comment by TheoKah** [comment]
https://discord.gg/3ZSt2cq

You can ask away in #general, explain what you want and what you tried. I'll be around tomorrow. Not really available right now as it is getting late here.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
