### ISSUE TITLE
Interaction permissions

### ISSUE THREAD

**Issue by demonte4509ui** [Arckenver/Nations#196]
so I claimed a area and now no one can interact with items and yes I set the perms and flags to allow it and it is still not working.

**Comment by TheoKah** [comment]
Are we talking about spawn? Minecraft protects the spawn already. You can set spawn-protection=0 in server.properties

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
