### ISSUE TITLE
Server console spammed in errors.

### ISSUE THREAD

**Issue by RainOfPain125** [Arckenver/Nations#197]
https://pastebin.com/MY8j5L8P

**Comment by Gobrunk** [comment]
You're sponge might be version 7.1 and you are using 5.1 methods. There is a branch up to date for the 7.1 version of sponge -> https://github.com/Arckenver/Nations/tree/api7

**Comment by RainOfPain125** [comment]
@Gobrunk Uhm.. Wheres the download? I don't know how to compile this stuff together.

**Comment by RainOfPain125** [comment]
If you mean this one, I was using it - https://github.com/Arckenver/Nations/releases/tag/v2.11_api7

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
