### ISSUE TITLE
Empty hand

### ISSUE THREAD

**Issue by Gobrunk** [Arckenver/Nations#198]
On branch api7, a player can open a chest when his hand is empty even if he is not allowed to interract on the claim. It might come from here, with the `isWhitelisted` which puts "air" as a whitelisted item :

```java
if (optItem.isPresent() && (ConfigHandler.isWhitelisted("use", optItem.get().getType().getId()) || optItem.get().getType().equals(ItemTypes.GOLDEN_AXE) && ConfigHandler.getNode("others", "enableGoldenAxe").getBoolean(true)))
			return;
```

**Comment by MineTears** [comment]
Is there any fix? I don't know what to do at all :(

**Comment by antoineok** [comment]
fix and pull request, you can now have a patched version by downloading this patched version (or building yourself the plugin)
[Nations211-2.11-S7.0-MC1.12.1_patch.zip](https://github.com/Arckenver/Nations/files/3828343/Nations211-2.11-S7.0-MC1.12.1_patch.zip)

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
