### ISSUE TITLE
How to only allow zone owners into chests

### ISSUE THREAD

**Issue by Coolkc456** [Arckenver/Nations#199]
I have the Nations plugin on my server to let players buy zones and then set up sign shops so players can warp to the zones and use the shops. How can I make it so that outsiders can't open chests in the zones? I have interact to deny for outsiders in the perms settings but it doesn't matter and players can still open the chests. :(

Right now the only solution is that zone owners have to place a block on top their chests when they are done managing their shop. Any help on this would be useful. Thanks in advance.

**Comment by antoineok** [comment]
Hello, this is patch,but you have to compile yourself the plugin in order to get the change

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
