### ISSUE TITLE
Admin commands

### ISSUE THREAD

**Issue by Arckenver** [Arckenver/Nations#2]
The plugin should have admin commands to change nation names, force player to join nation etc. These commands will be accessed using `/nationadmin`or `/na`.

Admin commands should make admins able to :
- Change a nation name
- Change a nation president
- Force player to join nation
- Force player to leave nation
- Give, take or set money to/from/of nation bank

Please comment below or on [official sponge forums thread](https://forums.spongepowered.org/t/flag-black-nations-v0-2-pre-release-towny-like-protection-plugin/12127/19) if you want to have other admin commands.

**Comment by SarahGreyWolf** [comment]
- Delete nation.
- Reset nation zones.
- Set Nations flags

**Comment by Arckenver** [comment]
- Create nations with no members
- Give golden axe for area selection purpose

**Comment by Arckenver** [comment]
See `/na` commands on the wiki for the full list of admin commands.
