### ISSUE TITLE
error occurred while executing command: null

### ISSUE THREAD

**Issue by scopefx** [Arckenver/Nations#200]
Hey, whenever i try to do "/n create test" it just says "error occurred while executing command: null".
Is there anything i can do about it?

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
