### ISSUE TITLE
EXPAND UP/DOWN

### ISSUE THREAD

**Issue by SKQRTY** [Arckenver/Nations#202]
Health to those who read this. I will be happy for your help. The fact is that I was faced with the problem of automatically expanding the territory up and down when creating a zone. Is it possible to turn off this seemingly convenient function?

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
