### ISSUE TITLE
Tombstone grave mod interaction

### ISSUE THREAD

**Issue by Zoneman1972** [Arckenver/Nations#206]
Hi there, Firstly, Thank you so much for picking this mod up and rejuvenating it. You are doing a great job and we truly appreciate your hard work.
May I make a small request please?
Can you please make a small amendment to the way Nations allows interaction with player graves (Corail Tombstone mod)
When a player dies on another players nation, they are unable to retrieve their grave due to interaction restrictions even though Corail Tombstone setting allows for the bypass of griefing protection 
(# Graves are allowed to bypass anti-griefing rules [default: true]
    B:graves_by_pass_griefing_rules=true)
Thanks again.

**Comment by Corail31** [comment]
@Zoneman1972 You can still sneak around to solve the interaction ;)

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
