### ISSUE TITLE
Nation is to close to another nation

### ISSUE THREAD

**Issue by RobertCUH** [Arckenver/Nations#208]
Hi I just made a server and the map isent the largest and my plan on the server is to have multiple nations on different islands but then I found out you cannot have a nation too close to another nation, is there anyway to decrease that distance so you can claim land for your nation near another nation.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
