### ISSUE TITLE
too many arguments

### ISSUE THREAD

**Issue by wldns0700** [Arckenver/Nations#209]
![image](https://github.com/Arckenver/Nations/assets/134362380/e3d66a90-02f9-4d71-9520-5f849f3e0b4a)

There are more args attached to the basic command, and it says that there are many args when executed. What should I do? I'm using Forge version 1.19.2.

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
