### ISSUE TITLE
Make admin nations ignore minNationDistance

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#22]
> admin nation
> Admin nations are nations without president, citizens, money, zones, or claimable block limit. They should be created and managed by admins using the /na commands. They can be used to protect special areas like your spawn.
> According to the information above, I think admin nation should ignore the limits like the distance with other players' nations and whether the name is the same as the players' nations. In addition, because "/n nation" cannot show admin nation, I think if there is a new command showing the list of admin nation, it can be better.
> # Admin nations
> 
> You're right, I'll make admin nations ignore the minimum distance requirement.

This problem is still existing. Admin nation still need to meet the minimum distance.
#6

**Comment by Arckenver** [comment]
You're right. I forgot that. I'll keep this issue opened until it's fixed.

Thanks for reporting.

**Comment by Arckenver** [comment]
Fixed as of f637f8c7aa61ab90fc07820833fe1715d7389e64.
