### ISSUE TITLE
Improvements on pvp protection system

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#25]
I have setted nation as no pvp status, but people still can use some ejection like bow to shoot others and hurt them.
Nation 0.10
spongeforge-1.8.9-1890-4.2.0-BETA-1666

**Comment by Arckenver** [comment]
You are right. Unfortunately, this is the normal behavior of Nations for now.

It would be nice to have bow shots canceled as well, so I mark this issue as a suggestion.

**Comment by 5igm** [comment]
Thank you very much.

**Comment by 5igm** [comment]
@Arckenver When server installed some magic mods, players also can use lightning, blowing, etc. to attack others. Thereby I suggest maybe you can create an option named damage (what residence did) to protect player from all of the damge.

**Comment by TheoKah** [comment]
Fixed by #77
