### ISSUE TITLE
About Area selection

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#28]
I think Residence's area selection is better than current selection method, because Residence's selection is a kind of three-dimensional method which is more flexible than two-dimensional method.
Is it possible to a Residence-like area selection way?

**Comment by Arckenver** [comment]
Unfortunately, the current two-dimensional system being strongly tied to Nations' core make it very hard to change. That would require to modify the way Nations store data, make its calculation to determine if areas collide etc. The current system has been chosen for two main reasons that would be lost if changing to a three-dimensional system : simplicity and performance.

**Comment by 5igm** [comment]
Ok. Thanks for your explain. @Arckenver
