### ISSUE TITLE
Features  suggest

### ISSUE THREAD

**Issue by PM47K** [Arckenver/Nations#29]
Hi dear programmers, in the first place sorry if i kill some word or my text is very strange, because my mother language is not english. Im here to suggest new features to your plugin nations.
If this is not possible or is stupid sorry i dont't know nothing about java code.
My suggests are: A admin permission command, that basically ask players to join a nation.
Like /invite nationmane player that can be put in a sign with a signcommand plugin and when a player clicks it he is invited to the nation refered on the command. Again sorry about the words i killed.
My second suggest is for the zones inside nations. Can you add a third zone claim point for height? And a block use permissions sistems in a way that if admins want they can only let player use door and chest to prevent maps with dirt 100 block height buildings(it gives bad look to server)?  Again sorry i probably killed many words and please let me know if you think this is a good idea and if you can add this to the next version.
Thanks for reading PM47K, Bye.

**Comment by Arckenver** [comment]
## Admin command to invite players into nations

That is a good idea. I'll keep that issue open until that feature is implemented.

## Height support for zones

That was also suggested by @5igm in issue #28. In brief, it's unfortunately not possible.

### Block use permission system

Sorry but I did not fully understand what you mean there. Could you reformulate using simple sentences ?

_N.B. Next time, don't hesitate to open multiple issues for each suggestion, it helps me keep track of each one without mixing them_

**Comment by PM47K** [comment]
Im building a server, and im using nations as a spawn. I would like to have players buying houses with /z buy command but i dont like to go to survival servers and see dirt houses. So basically that system would allow the admin too choose wich blocks the players could use/place. For example i would like to sell pre made houses that were impossible to brake or modify just a simple house for players use bed furnace and chest, that way the server map woud look more beautifull. Its like containers i think.
I once played a gta based minecraft server and they had appartments to rent in a big building that's why i suggested a height claim. But the permission blocks in zones do you understand the ideia?
Like, modify the permissions in a way that players can only oppen doors, open furnace to burn ores, oppen chest and use bed to sleep, and make it impossible to brake or place blocks.

**Comment by Arckenver** [comment]
I forgot about that but in fact, there already is such a command. It's `/na forcejoin <nation> <player>` (note that you also have `/na forceleave <player>`). See the wiki for a [list of all commands](https://github.com/Arckenver/Nations/wiki/Commands).
