### ISSUE TITLE
Permissions for blocks in zones

### ISSUE THREAD

**Issue by PM47K** [Arckenver/Nations#30]
I already tried to explain this idea (https://github.com/Arckenver/Nations/issues/29) but you adviced me to open multiple issues so here it is.
My idea is creating a permissions for zones that would let the admins configurate what players can do( place/brake/use)  in their zones. Like /permission.player.place.dirt-true something  like that if you understand. It's like something called containers i think. To explain better i am bulding a server that uses nations for spawn protection and i want it to be a kind of surival, but everytime i see some server survival based it has like dirt houses and it's very ugly. So i would like to sell zones in my spawn with pre build homes that are impossible to brake/modify, i would like players to buy them just for using chests, furnaces, crafting tables, enchanting table, open doors, and sleep im beds and stuff like that and make it impossible for them to brake or place blocks/lava/water/etc. I suggested the permissions because i think a system like that is very easy to configurate and very modular and it would be a complete protection, antigrifeing ,economy(players can buy zones) and of corse very funny with all the current features it has.

PS: If this is possible can it be mod compatible? (im using bibliocraft)

**Comment by PM47K** [comment]
Sorry about the english and did you understood what i meant?

**Comment by Arckenver** [comment]
Ok, I understand what you mean here. Unfortunately, such an idea does not go with the way Nations core was designed. So this system is not possible.

However, there might be a solution to your problem. You can set yourself as the zone owner and add players who buy the zone as coowners. This way you can edit the zone coowners permissions. The only thing is that you'll have to sell zones manually...
