### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by PM47K** [Arckenver/Nations#31]
Last issue i suggested creating a command that using a sign command when a player clicks it he is invited to the nation (https://github.com/Arckenver/Nations/issues/29) and you said there was already a feature like this witht he command forcejoin, but im having a problem. I want players to join my spawn nation so they can buy a house when im ofline , and i tried to use a command block but he is not accepting the marker @p so is there any way to make it auto recognize the player?

**Comment by Arckenver** [comment]
This is an error, which means it is not supposed to happen. The error can come either from you or Nations, that's what I want to know.

Is there any error message in the command block ? Also, what version of SpongeForge/SpongeVanilla are you using (including SpongeAPI) ?

**Comment by 5igm** [comment]
I has a similar problem early but it happened in nucleus.
https://github.com/NucleusPowered/Nucleus/issues/317
In addition, have you tried to use vanilla commands in command blocks with @p?
If vanilla commands also don't work, your permission plugin may has problem.

**Comment by Arckenver** [comment]
Any news on that issue @PM47K ?

**Comment by Arckenver** [comment]
I'm closing this issue because it doesn't seem active anymore.
