### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by GershonR** [Arckenver/Nations#34]
Set Spawn:
Users can create hundreds of spawns inside their claimed nation, can there be a config option to how many times someone can use /n setspawn ?

i.e
maxSetSpawns: 2

Information:
Add server join date to user info
Add zones owned to user info
Add a date when the current person owned the zone
Add a date when the town was created

Allow /nation info to show anywhere like /nation here so you don't have to stand at the nation to get information about your own nation

**Comment by Arckenver** [comment]
I've created an issue per feature you've suggested (#35, #36). Don't hesitate to create multiple issues for different subjects, it helps me keep track of things.

For your last point however I do not fully understand. `/nation info [nation]` gives description of the given nation if provided. If not provided, it gives description of the nation of the player executing the command.
