### ISSUE TITLE
Add information in citizen/nation/zone descriptions

### ISSUE THREAD

**Issue by Arckenver** [Arckenver/Nations#36]
@GershonR suggested to add information in some descriptions given by the plugin. Those are the ones that are possible (the others are not possible as the plugin doesn't store that kind of information).
- Add zones owned to citizen description
- ~~Add nation creation date in nation description~~

**Comment by Arckenver** [comment]
As adding nation creation date would introduce a break in backward compatibility. I finally won't add this feature.

**Comment by GershonR** [comment]
The players join date to server would also be nice to have in the citizens description

**Comment by Arckenver** [comment]
Unfortunately, for Nations to be lightweight, it doesn't store any player information. Therefore, it doesn't have any way to know when the player joined the server for the first time, or so I think. But maybe Sponge does permit that, I'd need to search further into this...

**Comment by GershonR** [comment]
When I join a nation and I use /n info, it says I must specify a nation even though I just want info for my own nation
