### ISSUE TITLE
Feature request - nation boundaires shown as particle effects when expanding your town.

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#39]
Request- when holding a golden and clicking the nation boundaries show with particle effects - red for nation boundaries and blue for zone boundaries.  I have seen this done with other plugins and it was fantastic.

**Comment by Arckenver** [comment]
That's a great idea ! However I don't quite see how it should look like, do you have any example of plugins using such a feature ?

**Comment by ProsperCraft** [comment]
https://dev.bukkit.org/bukkit-plugins/worldedit-selection-visualizer/

:)

**Comment by GershonR** [comment]
This would be very helpful to new players

**Comment by karolans** [comment]
Oh yes PLEASE! Any form of visualization would be great, I find it really difficult to work with the nation/zone boundaries at the moment. Just holding the golden axe could trigger the particles at least for now, if that makes it easier to code :).

**Comment by TheoKah** [comment]
Just pushed `/n show` that will do that in v2.4 :)
