### ISSUE TITLE
Polis Convertor 

### ISSUE THREAD

**Issue by GershonR** [Arckenver/Nations#4]
Command to convert the data

**Comment by Arckenver** [comment]
Would the idea be a [Polis](https://github.com/hsyyid/Polis) to Nations converter for data, so towns in Polis could be converted to their nation equivalents in Nations ?

If so, I'm not sure that would be a good idea, given that Polis uses a plot-based system. It would probably be possible but surely a lot of work for a tool that would be used for a very few people.

**Comment by GershonR** [comment]
Yep, and I would use it.

**Comment by Arckenver** [comment]
A python script would maybe be more suitable for this. We'll see when Nations will have its first official release (as we are still in pre-release).

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
