### ISSUE TITLE
Explosions and fire next to the nation but not inside destruct blocks

### ISSUE THREAD

**Issue by ghost** [Arckenver/Nations#41]
[This](https://github.com/Arckenver/Nations/blob/master/src/main/java/com/arckenver/nations/listener/ExplosionListener.java#L18) only checks the center of the explosion.
[This](https://github.com/Arckenver/Nations/blob/master/src/main/java/com/arckenver/nations/listener/FireListener.java#L19) only checks if a block is in the fire state in the nation but not if it is destroyed.

**Comment by Arckenver** [comment]
For the first one, indeed but I prefer it that way. However I know most of the other protection plugins do a per-block check. I think this is subject to debate but if you think we should go for a per-block check, you can make a pull request or I'll do it when a have more time (I'm a bit busy for now).

## 

For the second one, I guess you meant [line#26](https://github.com/Arckenver/Nations/blob/master/src/main/java/com/arckenver/nations/listener/FireListener.java#L26). But I guess checking for block destruction would also protect from any destruction, which is not what we want there, wouldn't it ?

**Comment by ghost** [comment]
For the second one, I was talking about the fact that a block in a nation cannot be set to fire state, but it can be destroyed because of fire next to it (and yes I meant the line 26).

**Comment by Arckenver** [comment]
Hmm indeed. However considering that fire shouldn't spread, it is in my opinion not a problem. Moreover, we can consider this feature as preventing fire spreading, not fire damage, as mentioned in the wiki.
