### ISSUE TITLE
Admin command to give nations extra blocks

### ISSUE THREAD

**Issue by Arckenver** [Arckenver/Nations#45]
Add admin command so nations can receive an unlimited amount of extra blocks given by admins (e.g. to claim a spawn).

`/na giveextra <nation> <amount>`

**Comment by TheoKah** [comment]
Can you make it so it also accepts  `/na giveextra <citizen> <amount>` ?
I can see a use in a webshop

**Comment by TheoKah** [comment]
`/na extra` and `/na extraplayer` will be available in next release
