### ISSUE TITLE
suggestion for wiki page

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#47]
https://github.com/Arckenver/Nations/wiki

A config guide would be helpful.

For example -     minNationDistance=400

400...blocks?...400 chunks?  400 what?

**Comment by Arckenver** [comment]
Good idea. I've started it [here](https://github.com/Arckenver/Nations/wiki/Config-Guide). I've also removed the restriction to collaborators only for wiki editing. Feel free to add your contribution.
