### ISSUE TITLE
Nation Upkeep Bug

### ISSUE THREAD

**Issue by GershonR** [Arckenver/Nations#48]
http://pastebin.com/5tcDeChN

http://i.imgur.com/lwZ6nJC.png

**Comment by Arckenver** [comment]
Already fixed in issue #43, but wasn't released in a new version.

Now [v2.1](https://github.com/Arckenver/Nations/releases/tag/2.1) and [v1.1](https://github.com/Arckenver/Nations/releases/tag/1.1) are out and contains this fix.
