### ISSUE TITLE
Claiming area for an Admin Nation

### ISSUE THREAD

**Issue by ghost** [Arckenver/Nations#56]
Hello, this list of commands on the wiki shows the command "/na claim <nation>" as a valid command but it doesn't show up on the in-game help for me and the command does not work properly. What is the way to claim area for an admin nation?

**Comment by Arckenver** [comment]
Yes that command exists and is properly coded, but I forgot to make Nations register it, which makes it unusable. Fortunately, @TheoKah fixed that in his [PR](https://github.com/Arckenver/Nations/pull/46).

The fix will be available in the next release of Nations.

**Comment by TheoKah** [comment]
https://forums.spongepowered.org/t/earth-africa-nations-v2-0-api-4-5-towny-like-protection-plugin/12127/148
<- this is fixed by https://github.com/Arckenver/Nations/pull/52
