### ISSUE TITLE
Lumber axe produces endless wood in protected areas.

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#58]
A normal axe does not break a log, but if you use a Tinkers lumber axe you get the logs and the tree doesn't break, so you get endless logs.

**Comment by Arckenver** [comment]
What is a Tinkers lumber axe ?

**Comment by ProsperCraft** [comment]
Tinker construct is a mod for Minecraft that is in almost every modpack, it has a lumbar axe that can take down an entire tree at once.  
http://tinkers-construct.wikia.com/wiki/Lumber_Axe

**Comment by Arckenver** [comment]
Then you should report to them, since Nations "do the right thing" when canceling the block breaking event.

**Comment by TheoKah** [comment]
Should be good after #96 is merged
