### ISSUE TITLE
The problem for admin nation, taxes, area selection and the suggestion for nation's levels system and message file

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#6]
1. admin nation

> Admin nations are nations without president, citizens, money, zones, or claimable block limit. They should be created and managed by admins using the /na commands. They can be used to protect special areas like your spawn.

According to the information above, I think admin nation should ignore the limits like the distance with other players' nations and whether the name is the same as the players' nations. In addition, because "/n nation" cannot show admin nation, I think if there is a new command showing the list of  admin nation, it can be better.
1. taxes
   I had found the option related to taxes in config file, but how can I use commands to change the taxes of a nation?
2. area selection
   When I used golden axe right click a block, it showed the message twice times.
   ![2](https://cloud.githubusercontent.com/assets/11610914/17277080/e2469b9e-576c-11e6-82fd-cb1ff8a37792.png)
3. nation's levels system
   I found there is a limit of nation's region. I suggests you can develop a level system like Towny. Then players can attempt to upgrade their nations. It will be more interesting.
4. message file
   Because my server uses different language, I tried to translate the message. However, after I translated the message file, I found the plugin still hasn't been translated completely. For example,
   ![1](https://cloud.githubusercontent.com/assets/11610914/17277065/8f619f78-576c-11e6-9893-640278445962.png)
   ![2](https://cloud.githubusercontent.com/assets/11610914/17277066/8f9a81d0-576c-11e6-97fa-fff23dc5e80b.png)
   ![3](https://cloud.githubusercontent.com/assets/11610914/17277067/8fd0371c-576c-11e6-942d-c85ace473a85.png)
   ![4](https://cloud.githubusercontent.com/assets/11610914/17277068/8fd1e9cc-576c-11e6-9ac3-18952c6c53b7.png)

**Comment by Arckenver** [comment]
## Admin nations

You're right, I'll make admin nations ignore the minimum distance requirement. 

I guess your talking about the `/n list` command. For that issue, I have two different ideas, let me have your opinion on them.
- Create a `/na list` command that would list all nations (admin & regular)
- Create a permission that would give the ability to see all nations when using `/n list`

## Taxes

To change a nation's taxes, use `/n taxes <amount>` as a nation staff member (president or minister). I forgot this command in the wiki, thanks for reporting it.

A staff member can edit tax only if `canEditTaxes` is set to `true` in config (true by default) and new taxes are below `maxTaxes` in config (100 by default).

## Area selection

Since you don't mention it, are you using Nations with the right version of SpongeAPI (that is 4.x.x) ? If so I'll try to figure out where does that come from.

## Nation's level system

Good idea ! I've created a new issue for that : #7

## Message file

That's surely because you've based yourself on the [english.conf](https://github.com/Arckenver/Nations/blob/100dbebdab04cf12c542ad9db97481aaad5b9f83/languages/english.conf) in the repo. My bad, the file is not perfectly up to date due to small frequent additions. I'm going to update it.

But for most of the things you're pointing out here, I'll add translation support very soon in v0.10 of Nations. Except for the red error `Too many arguments!` which comes directly from Sponge.

Also, I'd be really happy if you'd be willing to have your translation added to the official ones once it's finished !

**Comment by 5igm** [comment]
## 1. Admin nation

I support the second one which is "Create a permission that would give the ability to see all nations when using /n list", because according to the introduction of admin nation, admin nation actually is not a nation.

## 2. Taxes

This command didn't show in game when I typed "/n" as well. Additionally, when I tried to use "/n taxes" command, it showed some error.
This is the feedback in game.
![5](https://cloud.githubusercontent.com/assets/11610914/17278433/c9ac7450-578f-11e6-8613-a3eafb069d99.png)

This is the feedback in log.
`[02:26:26] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'n taxes 60' for source EntityPlayerMP['Deity'/290, l='world', x=-226.50, y=63.00, z=154.50]: java.lang.Integer cannot be cast to java.lang.Double
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
    at com.arckenver.nations.cmdexecutor.nation.NationTaxesExecutor.execute(NationTaxesExecutor.java:40) ~[NationTaxesExecutor.class:0.8]
    at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) ~[ChildCommandElementExecutor.class:1.10.2-2026-5.0.0-BETA-1599]
    at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:332) ~[CommandSpec.class:1.10.2-2026-5.0.0-BETA-1599]
    at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2026-5.0.0-BETA-1599]
    at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:274) [SpongeCommandManager.class:1.10.2-2026-5.0.0-BETA-1599]
    at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82) [bd.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
    at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:118) [PacketUtil.class:1.10.2-2026-5.0.0-BETA-1599]
    at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fl$1.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]`

**Comment by 5igm** [comment]
## 3. Area selection

My sponge version is "spongeforge-1.10.2-2026-5.0.0-BETA-1599"... I didn't notice this problem. Is this plugin for 4.x.x?

## 4. Nation's level system

Thanks for your praise. What is about another system-warfare system?

## 5. Message file

Originally I had planned to upload my translated message file after test. I am pleasured if I can help the development of an excellent plugin. After the new version released, I will upload the translation.

**Comment by 5igm** [comment]
One more suggestion, for now, the name of nation and spawn point only can be alphanumeric. Is it possible to support more languages?

**Comment by Arckenver** [comment]
_N.B. Although that's not a problem, next time don't hesitate to create an issue for each problem/suggestion. It doesn't bother me if there are lots of issues in the repo, and it helps make things clear, especially for people who would read this to see if their problem has not been already reported_ :wink:

_N.B. All new additions and problem solving mentioned below will be available in v0.10 of Nations_

## Admin nations

Great. Added as of commit bee6ad453dd08c971f4b1b2674f2f149ad14a181. Now uses permission `nations.admin.nation.listall` to be able to see all nations.

## Taxes

With commit f024d64068fd82fd9acb500a8b3c548a418e3929, nation taxes command appears when typing `/n`. It also adds a new line in the language file.

With commit f8abc4a2580689cee49e8ccb37b0a6a7a0345082, problem of `java.lang.Integer cannot be cast to java.lang.Double` is now solved. Thanks for reporting that one !

## Area selection

Indeed. Nations will target 5.x.x when it won't be marked as `bleeding` anymore. Hope this we'll as soon as possible.

## Nation's level system

I've also thought about that. I'm writing an issue for that, feel free to give your opinion when it'll be out.

## Message file

Great ! Thank you very much.

**Comment by 5igm** [comment]
Thank you very much!

**Comment by Arckenver** [comment]
@5igm In case you didn't see, Nations v0.10 and the new language file have been uploaded. Feel free to share your translation whenever you want. Also I didn't find you on the sponge forums, do you have an account there ?

**Comment by 5igm** [comment]
@Arckenver Yes, I have, but I hardly ever left messages in that website. I just replied you with the translation file in your sponge thread. Thanks for your help.
https://forums.spongepowered.org/t/earth-africa-nations-v0-10-pre-release-towny-like-protection-plugin/12127/66

> Jinlin_Chen3m
> Hi, Arckenver. I have finished the translation file. I tried to upload this file in this website, but it didn't support it. Thereby I uploaded it in here: https://my.pcloud.com/publink/show?code=XZKE0fZxoBkFN1pcq5yCgRjYPD8a8M6g10y
> It is a chinese translation.
