### ISSUE TITLE
Users being added multiple times to a nation.

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#60]
From a player on the server--
"okay so i dont know if its when the server reboots, or if it crashes.. however when you add someone to you nation, then make them a co-owner of a zone it re-adds them to your nation.. so i have Benorack 4x, Ban_Pan 4x, Xenobea, 3x...
so it shows 16 people in the nation, when i should only have 8"

If you would like to visit, we have some amazing nations- infinitylite.prospercraft.com

**Comment by Arckenver** [comment]
This should also have been fixed by @TheoKah's commit 10443197dd68b1c257371e57ccb0bf8b1c4fd62b. We'll see in v2.2.

**Comment by Arckenver** [comment]
See #61.
