### ISSUE TITLE
Coowners have to be added after each reboot, not saving?

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#61]
After each reboot co-owners of nations have to be reappointed because they are forgotten after each reboot.

**Comment by TheoKah** [comment]
Fixed by [this commit](https://github.com/Arckenver/Nations/commit/10443197dd68b1c257371e57ccb0bf8b1c4fd62b)

This will be live on next release.

**Comment by Arckenver** [comment]
It's high time we release a new version then. I'll do it today.

**Comment by Arckenver** [comment]
See [v2.2 release](https://github.com/Arckenver/Nations/releases/tag/v2.2).
