### ISSUE TITLE
Using redstone in a nation not your own causes the server to lock up.

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#63]
https://github.com/SpongePowered/SpongeForge/issues/1054

**Comment by GershonR** [comment]
Any news on this? Seems like a big bug

**Comment by TheoKah** [comment]
I tried a lot of combinations testing for #65 and saw no crash

I'll close this issue for now. Please reopen after PR #77 is merged and released if the error still occurs
