### ISSUE TITLE
Feature Request - plot info on walking on to a plot show owners name

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#67]
Towny would show the owners name when you walked on to a plot, that was really helpful and nice, please add?

**Comment by TheoKah** [comment]
The name of the zone already shows up in chat when entering. Does renaming it to a player's name can do the trick or you think owner should ne displayed anyways?

**Comment by ProsperCraft** [comment]
No because on high population servers, the plot could turn over several times, it wouldn't make sense having the plot be named after 3 owners previous.

**Comment by TheoKah** [comment]
This can be done for sure, but I don't want the line to be too long...
@Arckenver ? do you think this is ok if we make the zones' name optional?
My idea would be to remove the possibility to handle a zone by name as one can do it by standing on it.
The name would only appear on /z info and when entering a zone (if not blank)

**Comment by TheoKah** [comment]
Should be good after #96 is merged
