### ISSUE TITLE
Config File Overwriting and Not Saving Changes

### ISSUE THREAD

**Issue by jelaw21** [Arckenver/Nations#71]
Forge .2123
Minecraft 1.10.2
Nations 2.2
Sponge v. 5.x

Everytime I try and change the config file for prices for nations and land claim, it overwrites it on every restart.

**Comment by TheoKah** [comment]
Have you tried to /na reload after you made the changes and before you restart the server?

Are the values still overwritten even if you make them when server is stopped?

**Comment by ProsperCraft** [comment]
Check file permissions make sure the user the server you are running as has rights to edit the file.

Also try editing the file while the server it not running.

**Comment by jelaw21** [comment]
I am sorry, the /na reload got it and kept it!!  Thanks.

**Comment by ProsperCraft** [comment]
If it is resolved, close your issue?
