### ISSUE TITLE
Prefixes, and /n replacement

### ISSUE THREAD

**Issue by merjilin** [Arckenver/Nations#72]
Greetings, I am writing this because I believe that the suggestions I am about to give will improve this plugin. Firstly, I would like to say thank you for developing a pretty brilliant protection plugin for the sponge API, particularly with it being as finicky as it is. Now down to business, I, and my fellow staff and players, believe it would be beneficial to add prefixes to chat, regarding the nation they're stationed in and lastly, I think replace the current /n with /n info, then using /n to give information about the nation the player is stationed in would make this plugin less confusing for new players. Especially due to new players automatically going to use the /n command, then being confronted with information about the plugin version etc. Thank you for taking your time to read this, and I hope these suggestions are evaluated (and hopefully implemented) when possible -merjilin (head-admin of GrandiCraft Servers)

**Comment by TheoKah** [comment]
Hey,

The chat tag is already implemented in my dev branch and will be available with my next merge

I like the idea of having info on /n and add the commands on /n help and/or /n ? (same with /z)
I will need @Arckenver 's green light before I change this because it changes the way the plugin behaves

However if we want to mimic towny, /n should not give info about the nation one is standing on, but on the nation player is in.

**Comment by merjilin** [comment]
Thank you for the fast reply, I'm used the developers leaving it a week or two, or never even replying so this is a lovely change. Fantastic that the tags are soon to be released, and as for the /n giving info about the nation the players is in, I think I must have got my wording wrong, as this is what I meant to convey, sorry :D 
Also, sorry to add this here, but is there a way for an admin to bypass nation protection? I've only just had an issue with it when trying to investigate something on my server.

**Comment by TheoKah** [comment]
You can bypass protection giving admins `nations.admin.bypass.perm.build` and 
`nations.admin.bypass.perm.interact`

https://github.com/Arckenver/Nations/wiki/Permissions

**Comment by merjilin** [comment]
Oh whoops my bad. I must have just missed those whilst going through the list, sorry.

**Comment by TheoKah** [comment]
@Arckenver can you validate we transfer `/n info` on `/n` and `/n` on `/n help,h,?` ?

**Comment by Arckenver** [comment]
Yeah that's not a bas idea given that Nations is highly inspired by Towny !

I validate these changes !

**Comment by TheoKah** [comment]
Should be good after #96 is merged
