### ISSUE TITLE
Itemframe Dupe Bug

### ISSUE THREAD

**Issue by GershonR** [Arckenver/Nations#75]
1. Place something in an item frame
2. Reload the chunk by leaving it and waiting for some time
3. Come back and there's fallen item frames but they are still on the wall

This happens only in nations

**Comment by GershonR** [comment]
This seems to also happen with items left on the ground. The items won't despawn and will be deplicated and items can be duped to stacks within minutes

**Comment by GershonR** [comment]
Update: I think this is an entity problem because it is now duping peoples pigs and horses in their towns, and it's starting to blow up their animal populations

**Comment by TheoKah** [comment]
I think I know how to prevent this. I'll fix it asap

**Comment by TheoKah** [comment]
Should be good after #96 is merged
