### ISSUE TITLE
Console spam regarding player event

### ISSUE THREAD

**Issue by merjilin** [Arckenver/Nations#76]
They there, sorry to be back so soon, but my server console has started to experience some pretty persistent spam. Log: http://pastebin.com/VQ09eENE This might just be a sponge issue, but I feel it is best to make you aware of it.

**Comment by ProsperCraft** [comment]
Same problem here - https://gist.github.com/ProsperCraft/7b0a6300c6c981485738aaba8c337ce0

Could not pass ChangeBlockEvent$Place$Impl to Plugin

[09:21:31] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-428c0b2
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2022
    Minecraft Forge: 12.18.3.2185

**Comment by TheoKah** [comment]
This is due to fake players (block placers)
I fixed it on the dev branch... I think It's time for a release. I'll make a PR tomorrow for @Arckenver to release it asap

**Comment by TheoKah** [comment]
Fixed in #77
