### ISSUE TITLE
Claim Blocks & API Suggestion

### ISSUE THREAD

**Issue by Shane1199** [Arckenver/Nations#78]
I'd like to have a feature where /nationsadmin can add claim blocks to a nation, bypassing having to pay for them and the limit that would be there. This is helpful for Rankup or RPG servers, and possibly donators.

EDIT: Having an API so that developers can code addons or unique functions to add neat things such as Nation Quests, Nation Warps, Nation Jail, etc. Although adding them into it or as an additions.jar would be great too.

EDIT 2: I believe this partly references: #45

**Comment by TheoKah** [comment]
An admin can already select an area and `/na claim NATIONNAME` to claim land into any nation, bypassing any money, size and distance between other claims requirements.

As for the API, this would be for @Arckenver to answer

**Comment by Shane1199** [comment]
The adding claim blocks to a nation idea is for servers that may give claim blocks as some type of reward.

**Comment by TheoKah** [comment]
I'll do that as well

**Comment by TheoKah** [comment]
`/na extra` will be available in next release

**Comment by TheoKah** [comment]
About the API, we already have a service that allow other plugins to:
* get the nation name from a player UUID
* get the nation name from a location
* check if a player is in a nation
* check if a player is president of a nation
* check if a player is minister of a nation

If you have more ideas, we can add them

**Comment by Shane1199** [comment]
I think that is good.
