### ISSUE TITLE
Not support join operation?

### ISSUE THREAD

**Issue by luniHw** [Arckenver/Nations#79]
/**/PreparedStatement prep0 = conn0.prepareStatement("delete svc, seg from t_lcm_service_operation as svc left join t_lcm_svcsegment_operation as seg on svc.serviceId = seg.serviceId where\n        svc.serviceId = ?");
2017-01-19 19:22:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SVC" not found; SQL statement:
delete svc, seg from t_lcm_service_operation as svc left join t_lcm_svcsegment_operation as seg on svc.serviceId = seg.serviceId where
        svc.serviceId = ? [42102-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)

**Comment by TheoKah** [comment]
This trace is not nation related...

**Comment by TheoKah** [comment]
Closing as this is probably not Nation related
