### ISSUE TITLE
The suggestion for more language in nation's name and spawn point

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#8]
For now, the name of nation and spawn point only can be alphanumeric. Is it possible to support more languages?

**Comment by Arckenver** [comment]
I guess so. For now, Nations uses regex `[a-zA-Z0-9]*` (which means alphanumeric) to validate a nation name. It would be a good idea to extends it to letters with accents, ideographic characters etc.

I'm investigating that.

**Comment by Arckenver** [comment]
_N.B. Below corrections will be available in Nations v0.10 and higher_

With commit d918279479b5d5c21c2f49f54de58217f18e82fb, regex is now `[\p{Alnum}\p{IsIdeographic}\p{IsLetter}]*`, allowing letters and ideographic characters such as kanjis. 

Please report any group of character that would still not be supported.

**Comment by 5igm** [comment]
Thank you very much.
