### ISSUE TITLE
Fees-system question | Bypassing fees option

### ISSUE THREAD

**Issue by crymates** [Arckenver/Nations#80]
Currently taxes do not work for me :/
OR: Paxes get payed every REAL day (which I don't know).
The best would be to make it changeable in conf-file.

`fees_rate = 24000`

for paying fees automatically as player every 24000 ticks to nation account.

Greetz,
Hannes

**Comment by crymates** [comment]
So it's more real-like (e.g. paying fees every minecraft day) :P

**Comment by crymates** [comment]
Can you just explain the fees system?
When players do need pay fees?
It's automatically payed every day, but I don't know when. Also offline players are affected, that's really good ;]

So it's not needed anymore paying in ticks.

But an idea could be bypassing fees for specific members, not only nation staff.

Greetz,
Hannes

**Comment by TheoKah** [comment]
Taxes are paid every day at 12:00:00 (server time)
Admin nations are exempt of upkeep
Presidents and Ministers do not pay taxes

Upkeep for nation is a fee per citizen (can change the base in the config)
Taxes are set by the nations staff (can set a maximum in the config)

**Comment by crymates** [comment]
This is really helpful.
Thx alot!

**Comment by crymates** [comment]
Well, and about the bypassing option?
Is this something u could add? ;]

**Comment by TheoKah** [comment]
Next release will make it so players with permission node `nations.admin.nation.exempt` won't be taxed.
(Nations will still have to pay an upkeep)
