### ISSUE TITLE
Edit zone and nation names

### ISSUE THREAD

**Issue by crymates** [Arckenver/Nations#81]
Please add the possibility to edit nation and zone names.
Also, it's not possible to set e.g. "Mr. Flintstone" as zone-name, bc. just one word is allowed.

Could you change it in like `/z create "Mr. Flintstone"`
The "" are important then.

Greetz,
Hannes

**Comment by crymates** [comment]
Also for editing names just

`/n edit "Handorian"` for the nation you stay in.
`/z edit "Mr. Meyer" `for zone you stay in.

Greetz ;]

**Comment by TheoKah** [comment]
Nations names can be changed by admins using /na setname
Zones names can be changed by nation staff with /z rename

I'll see what I can do for the spaces in names. I think I'll take the towny approach replacing underscores ( _ ) in nations/zones' names by spaces

**Comment by crymates** [comment]
Nations names changed by admins - accepted, tested, alright ;]
`/z rename` does not work, neither for nation stuff and/or admins.

Ya, spaces would be great.
At this moment you can change the names in the config and it works fine, but, it's alot of work and not that easy to handle.

**Comment by turtledude01** [comment]
In #86 I added extra symbols (-_.) to the allowed characters in nation and zone names. which would allow you to use ( _ ) as a space.  
I'm currently waiting for the devs, who seem to be inactive(?) for a period of time.

**Comment by TheoKah** [comment]
Should be good after #96 is merged
