### ISSUE TITLE
Item Frame doesn't claim

### ISSUE THREAD

**Issue by Shane1199** [Arckenver/Nations#82]
I tried having item frames in my Shop at Spawn, which is definitely protected as I just tested with it. It is in an Admin nation with 0 players. Anyone can walk up, tilt the item, and remove the item. I'm not sure if this works for non-Admin nations however.

Latest Nations version
Minecraft: 1.10.2
SpongeAPI: 5.1.0-SNAPSHOT-d41d606
SpongeForge: 1.10.2-2202-5.1.0-BETA-2070
Minecraft Forge: 12.18.3.2202

**Comment by Shane1199** [comment]
Update: We do have Container-Access allowed for all players.

**Comment by TheoKah** [comment]
Should be good after #96 is merged
