### ISSUE TITLE
Suggestion - Nation Chats

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#83]
Hey friend :)

Suggestion for Nation specific chats, option to ignore it, spy on them (for staff), toggle or write a single message.
Possible commands:
/n chat ignore
/n chat <msg>
/n chat toggle (All messages are now in nation chat)
/na chatspy

**Comment by TheoKah** [comment]
In next version (2.4)
- Added `/nc` as an alias of `/nation chat`
- `/nc message` now directly send the message
- `/na spy` will allow admins to spy on nation chats
- `/na` with no parameters toggle the channel on/off

I don't like the idea of a nation chat ignore for two reasons:
1. 'spammers' might quit nation chat to spam general chat instead
2. one can already mute all chatbox if doesn't want to be bothered by chat

Feel free to re-open if you want to discuss that last point
