### ISSUE TITLE
Suggestion - Using a "server" economy account

### ISSUE THREAD

**Issue by turtledude01** [Arckenver/Nations#87]
The basic idea behind this is, Money gets paid to the server account anytime someone spends money that would normally just get deducted, and vice versa, money gets paid from the server account back into a player or nation on a refund or anything.

**Comment by yepidoodles** [comment]
I'm curious at what purpose this could hold.

**Comment by turtledude01** [comment]
I use things like this for a "closed economy" where money can't be created or destroyed.  Makes for a more realistic economy

**Comment by turtledude01** [comment]
I've actually done most of the work on this with my fork of the repo

**Comment by turtledude01** [comment]
I added this almost fully in #86 
Only thing i did not check for is if the server account doesn't have enough money to afford a /n unclaim refund.  I believe that currently it would pay the player the amount owed, and just cancel the transaction on the server account.

**Comment by TheoKah** [comment]
Apart from the refunds, I see no action that would give money to a player in the current implementation.

The plugin will create money only in the case you set it to refund more than the actual cost of a block, but such a setting would be a huge loophole.

This would end up in a huge virtual account that cannot be emptied anyways, so might just keep it infinite as well...

**Comment by turtledude01** [comment]
If you don't mind, and have the time to do so, take a look at my fork where I added quite a lot of things, including this. 
My idea behind this was a closed eco where money cannot be created or destroyed.  I modified both Nations and an admin shop plugin to fulfill this for myself since it is a major thing in the design of my server.

**Comment by TheoKah** [comment]
I think this would be a mistake to make nation handle economy as well.
You should work directly on an closed economy plugin (as long as it respects sponge's api, nations will be compatible).

No need to touch nation for this.

**Comment by turtledude01** [comment]
I don't actually understand how this can be accomplished so ill talk with my dev friends about it...

**Comment by TheoKah** [comment]
Tell me if your friend don't know either. I got an idea that should work just fine

**Comment by turtledude01** [comment]
@TheoKah Seems my friends don't believe this should be a seperate plugin and that plugins should just support this option themselves, since its such a small addition (I should know since I actually did the work for this on my branch)

**Comment by TheoKah** [comment]
Let say I'm using this list of plugins:
- Protection where I can buy protected land
- Adminshop where I can sell buy items
- Job plugin that give player money on a regular basis
- Plugin that add say coins to global economy everytime a player has an achievement

You would need to make sure every single plugin respect the closed economy system. This is a lot of work.

Solution would definitely be to make a specific economy service to implement the sponge api ( https://docs.spongepowered.org/stable/en/plugin/economy/index.html )

There are 3 actions in an economy service:
* Deposit: Occurs when an account has funds added to it
* Withdraw: Occurs when an account has funds removed from it
* Transfer: Occurs when an account exchanges funds with another account

All you have to do is to make sure your economy plugin handle deposit and withdraw correctly by using a third account and force a `TransactionResult` to fail if there is not enough money in the bank.

**Comment by turtledude01** [comment]
Ill look at doing this myself within a week or 2.  To make sure that this does not fail when I do it, Does /n unclaim still unclaim the land if the eco check fails?

**Comment by turtledude01** [comment]
After taking a quick look through the eco API, I will be making a plugin called "Closed Eco" soon.

**Comment by turtledude01** [comment]
@TheoKah I made the plugin and it works flawlessly with Nations :D https://github.com/Radical-Delta/ServerEco

**Comment by TheoKah** [comment]
@turtledude01 Noice!
