### ISSUE TITLE
Suggestion - Permission per nation

### ISSUE THREAD

**Issue by crymates** [Arckenver/Nations#88]
Hi,

to prevent users to spy other nations and to set an "main" nation for default players it's the best if every nation has it's own permission, like: `nations.command.join.honain` for the kingdom "Honain".
So just players with that permission are able to join the nation.

Greetz,
Hannes from Germany

**Comment by crymates** [comment]
-PUSH-

**Comment by TheoKah** [comment]
What do you mean "to spy other nations" ?

I can easily add a default nation new players auto-join on first join. But this would imply you will need players to leave it before they can make their own or joins another one...

As for the special permission to join nations, this is easily doable too.

May as ask how you would like to use it with an example? just to make sure I understand correctly what you expect

**Comment by turtledude01** [comment]
I think I see what @yololetsplay is looking for here.  I feel that they want to be able to have multiple ranks on the server, and within each rank you can join a certain 'public' nation that REQUIRES you to be in a certain group.  Even if this isn't what @yololetsplay wants, I feel it still fits with the discussion on this one and would be a nice addition for many servers.

**Comment by TheoKah** [comment]
This can be added, servers that do not want to limit players can just add `nations.command.join.*`
I'll look into it

**Comment by crymates** [comment]
I mean that if an nation is open, everybody can join and leave all the time and spy them. How they think about other nations and so. That's the point why extra permissions are better ;] Seems like it does the same which u implement ;]

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
