### ISSUE TITLE
Bugs - Dupe items

### ISSUE THREAD

**Issue by crymates** [Arckenver/Nations#89]
Hi,

if you e.g. save an zone or nation against "BUILD" the players can place water on an field (carrots, potatoes, everything) and they dupe the items without destorying the field. Like, invinite ressources.
Same for item frames: If you hit one which is in an protected zone or nation, u dupe the item without drop the item from frame.

Greetz,
Hannes from Germany

**Comment by TheoKah** [comment]
The item frame part should now be fixed with PR #96

I'll see if I can easily prevent liquids (not just water) from entering a nation

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
