### ISSUE TITLE
The suggestion for a reload command

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#9]
I suggest to add a command to reload the config file. I trust it will be more convienient to edit the config file.

**Comment by Arckenver** [comment]
With commit 570d784f5cfe13b4b6fc567a17f0b4e7677ea06f, Nations now have command `/na reload` (requiring permission `nations.command.nationadmin.reload`) that reloads config file.

**Comment by 5igm** [comment]
Thank you very much.
