### ISSUE TITLE
Request - Add "%player% entered %zone%" in server console

### ISSUE THREAD

**Issue by crymates** [Arckenver/Nations#90]
Hi,

Could you please add an function so that you can enable in config file that it get logged if players enter another zone?

Like:
```
Tester123 entered Honain.marketplace
King442 entered Honain.fightclub
Jack56 entered Honain
```

It would be great so I could combine this with teamspeak so that if an player enters an area he/she get's moved to an teamspeak channel.
It's the best thing for rpg servers then ;]

Also it's interesting for server admins, where do people go, which ways, all these things.

Greetz,
Hannes from Germany

**Comment by crymates** [comment]
-PUSH-

**Comment by TheoKah** [comment]
Should be good after #96 is merged
