### ISSUE TITLE
Suggestion: /n costs

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#91]
Super simple command to show players the configured costs of:
- Nation creation
- Outpost creation
- Amount per block claimed
- Amount per extra claim block
- Taxes
Etc.

**Comment by crymates** [comment]
Great idea!

**Comment by turtledude01** [comment]
I added this in #86 along with a lot of other fun things
It seems that the devs of Nations have been inactive for some time so I took it upon myself to add/modify the things I felt needed to be in the plugin.

**Comment by crymates** [comment]
So could you please please add my request of show it in console when someone moved to another region?

[https://github.com/Arckenver/Nations/issues/90](https://github.com/Arckenver/Nations/issues/90)

Greetz,
Hannir

**Comment by TheoKah** [comment]
I've been away for 2 weeks, I'll review a lot of local code today and push it soon. This is already implemented in my local version.

**Comment by crymates** [comment]
You mean the console output for #90 ? ;]

**Comment by TheoKah** [comment]
Both console output when entering a region and the /n costs as well as many other things I couldn't push earlier

**Comment by crymates** [comment]
Great job dude!

**Comment by TheoKah** [comment]
Should be good after #96 is merged
