### ISSUE TITLE
Advice - German translation does not work

### ISSUE THREAD

**Issue by crymates** [Arckenver/Nations#92]
Hi,

like the title says, the translation does not work, because ö, ä and ü are not supported.
Nations just do not start if something is incorrect.

Greetz,
Hannes from Germany

**Comment by TheoKah** [comment]
I had it working correctly using [this file](https://github.com/Arckenver/Nations/blob/master/languages/german.conf)...

[screenshot](https://i.gyazo.com/65bfa3e03453e95c05622ccd8c883dee.png)

Do you have logs about this?

**Comment by crymates** [comment]
It was my own fault - forgot "" in some lines :/
