### ISSUE TITLE
Suggestion - Few things about "admin" nations zones

### ISSUE THREAD

**Issue by turtledude01** [Arckenver/Nations#93]
So i've been using this plugin for a while, even did a few modifications to it to make it fit more with towny and whatnot, but I have a small request.  Currently in an Admin nation, any player can /z buy on a plot, but that player cannot then turn around and sell that plot themselves as they get the error "You must be the owner of the zone" or something similar (language file code: GV) Thanks for all the work you've put in!

**Comment by turtledude01** [comment]
I added this in #86 a while ago

**Comment by TheoKah** [comment]
I made it so the zone in admin area cannot be sold by the zone owner.

I'm using the mechanic to sell "shop plots" at spawn to players. If they were able to sell the plots back, I would have rich end game players buy the plot and sell them back for a small price.
Another problem would be that the zone sell mechanic won't give money to the player.

I think the best way here is to have an admin manually dealing with the zone (allowing him to refund the player if that's your server's policy)

The message itself is a bit misleading indeed, I'll see if I can change that

**Comment by turtledude01** [comment]
Could you at least allow an option to allow players selling admin nation plots owned by them? If you decide against it then I will probably be keeping my own fork of Nations with the few modifications my server needs.

**Comment by turtledude01** [comment]
What I was really going for with this, was making it as similar to a real life system as possible, Make it to where if I Buy land in an  Admin nation, I can sell it with ought having to ask to sell it, then forcing the admins to do it.  I've already seen this work out perfectly on my server. Someone bought a plot they didn't really want, and sold it for LESS than they paid for, within an hour it was bought by a new player, and that money automatically went to the previous owner.  Worked out AMAZINGLY.  That being said, I do somewhat see your point of view.  Now seeing both sides, I can understand that there should probably be a Config option for enabling this behavior.  It is probably one of the only things my fork is lacking on config options.  Now, if you would like me to just stop asking for functions that I know take only a few minutes to add in as optional features, then I will stop asking and just do it myself.  

Sorry if any of this sounds harsh or rude at all.

**Comment by TheoKah** [comment]
I think I'll do the following:

- Keep the admin nation not using economy, if you want a nation with economy, make a normal nation ( issue #87 )
- Make it so 'open' zones can be bought by outsiders in non admin nation ( issue #85 )
- Keep the zone sell as it is: cannot sell a zone in admin nation, but you can for non-admin ones. If the zone already had an owner, the old owner get the money, if not, the nation get the money

This way, in your case, you will be able to have a normal nation where outsiders can buy/sell zones.
Only requirement would be you need a 'real' player to own the nation...

**Comment by turtledude01** [comment]
Guess Ill just keep my own fork with things like this for anyone that wants extra optional features
