### ISSUE TITLE
Better lang file layout

### ISSUE THREAD

**Issue by turtledude01** [Arckenver/Nations#98]
Currently the lang file is like "AA"="i dont know what this is for" when it should be more like 
"command.help.nationCmd" = "Shows info about a nation"

**Comment by TheoKah** [comment]
I agree. I'll change the "XX" codes for something more efficient

**Comment by yepidoodles** [comment]
I would like to do this, but I need to know what sort of format you want to use. @TheoKah

**Comment by TheoKah** [comment]
This will be the next thing I do after v2.5

This is a mess and I want to do it correctly.

I plan to use human readable IDs instead of random letters

**Comment by TheoKah** [comment]
Done -> https://github.com/Arckenver/Nations/releases/tag/v2.6
