### ISSUE TITLE
Add '/n tag' '/na tag' '/n removetag' and '/na removetag' + more chat tag options

### ISSUE THREAD

**Issue by turtledude01** [Arckenver/Nations#99]
This is a multi part request (which once again I did on my repo because its something I really like)

All of this is basically just for chat.  

Part 1: the /n tag step-
In this part, I would like to allow /n tag <tag> to accept 2-4 characters (letters or numbers) which will be used in chat in place of the Nations name if they are set. The reason behind this is because the chat tags get VERRY long VERRY quick.  

Part 2: more chat options-
In this part, I would like the options to have the nations Persident's tag (count, leader, whatever is set in the config groupings) to be shown in chat with their prefix of the nation.  

And as a side bonus, add more config options for the chat, allowing for us to configure how the tag LOOKS,  by allowing regex replacements for {Nation} {NationTag} {NationTitle} (nation title, should be blank unless they are either A. a minister or B. the president)

Thanks for your consideration, and as always, if you decide against this idea, then I will be continuing to support it myself on my fork of Nations.  Thanks!

**Comment by TheoKah** [comment]
All great ideas. I'll add that

**Comment by TheoKah** [comment]
Added `/n tag` and `/na tag` in v2.5 (release in a couple hours)

Added a format string for the chat header with placeholders:
`{NATION}` -> nations's tag or nation's name if there is no tag
`{TITLE}` -> the title of the player:

- if `enableNationRanks` is false -> empty string
- if President -> use the `presidentTitle` in the config depending on number of citizens in nation
- if Minister -> string `LQ` in language file (defaults to "Minister")
- if Citizen -> string `IS` in language file (defaults to "Citizen")
- if not in nation -> string `LR` in language file (defaults to "Hermit")

I'll change the language ids soon for a more readable form. Keep an eye on the wiki to have the most up to date values
